<?php
declare(strict_types=1);

namespace App\Admin\Repository;

use PDO;

final class CompanyAdminRepository
{
    public function __construct(private readonly PDO $connection) {}
    public function summary(): array { $row=$this->connection->query("SELECT SUM(status='ativo') ativos,SUM(status='pendente') pendentes,SUM(status='bloqueado') bloqueadas,COUNT(*) total FROM empresas")->fetch()?:[];$linked=$this->connection->query("SELECT COUNT(DISTINCT empresa_id) FROM empresa_integracoes WHERE sistema='SO' AND entidade='fornecedor'")->fetchColumn();return ['ativos'=>(int)($row['ativos']??0),'pendentes'=>(int)($row['pendentes']??0),'bloqueadas'=>(int)($row['bloqueadas']??0),'vinculadas'=>(int)$linked,'total'=>(int)($row['total']??0)]; }
    public function list(array $filters=[]): array { $search=trim((string)($filters['search']??''));$page=max(1,(int)($filters['page']??1));$limit=min(100,max(1,(int)($filters['per_page']??25)));$sql="SELECT e.*,i.identificador_externo AS so_fornecedor_id,COALESCE(u.total_usuarios,0) total_usuarios FROM empresas e LEFT JOIN empresa_integracoes i ON i.empresa_id=e.id AND i.sistema='SO' AND i.entidade='fornecedor' AND i.status='ativo' LEFT JOIN (SELECT empresa_id,COUNT(*) total_usuarios FROM empresa_usuarios GROUP BY empresa_id) u ON u.empresa_id=e.id";$params=[];if($search!==''){$sql.=' WHERE e.razao_social LIKE :s OR e.nome_fantasia LIKE :s OR e.documento LIKE :s';$params=['s'=>'%'.$search.'%'];}$sql.=' ORDER BY e.atualizado_em DESC,e.id DESC LIMIT :limit OFFSET :offset';$stmt=$this->connection->prepare($sql);foreach($params as $key=>$value)$stmt->bindValue(':'.$key,$value);$stmt->bindValue(':limit',$limit,PDO::PARAM_INT);$stmt->bindValue(':offset',($page-1)*$limit,PDO::PARAM_INT);$stmt->execute();return $stmt->fetchAll(); }
    public function find(int $id,bool $lock=false): ?array { $stmt=$this->connection->prepare("SELECT e.*,i.identificador_externo AS so_fornecedor_id FROM empresas e LEFT JOIN empresa_integracoes i ON i.empresa_id=e.id AND i.sistema='SO' AND i.entidade='fornecedor' AND i.status='ativo' WHERE e.id=:id LIMIT 1".($lock?' FOR UPDATE':''));$stmt->execute(['id'=>$id]);$row=$stmt->fetch();return $row===false?null:$row; }
    public function findByDocument(string $document,bool $lock=false): ?array { if($document==='')return null;$stmt=$this->connection->prepare('SELECT * FROM empresas WHERE documento=:documento LIMIT 1'.($lock?' FOR UPDATE':''));$stmt->execute(['documento'=>$document]);$row=$stmt->fetch();return $row===false?null:$row; }
    public function findByExternalSupplier(int $supplierId,bool $lock=false): ?array { $stmt=$this->connection->prepare("SELECT e.* FROM empresa_integracoes i INNER JOIN empresas e ON e.id=i.empresa_id WHERE i.sistema='SO' AND i.entidade='fornecedor' AND i.identificador_externo=:id LIMIT 1".($lock?' FOR UPDATE':''));$stmt->execute(['id'=>(string)$supplierId]);$row=$stmt->fetch();return $row===false?null:$row; }
    public function create(array $data,int $createdBy): int { $uuid=$this->uuid();$stmt=$this->connection->prepare('INSERT INTO empresas (uuid,razao_social,nome_fantasia,documento,tipo_pessoa,segmento,contato,telefone,email,inscricao_estadual,inscricao_municipal,endereco_logradouro,endereco_numero,endereco_complemento,endereco_bairro,endereco_cidade,endereco_uf,endereco_cep,status,criado_por) VALUES (:uuid,:razao_social,:nome_fantasia,:documento,:tipo_pessoa,:segmento,:contato,:telefone,:email,:inscricao_estadual,:inscricao_municipal,:endereco_logradouro,:endereco_numero,:endereco_complemento,:endereco_bairro,:endereco_cidade,:endereco_uf,:endereco_cep,:status,:criado_por)');$data['uuid']=$uuid;$data['criado_por']=$createdBy;$stmt->execute($data);return (int)$this->connection->lastInsertId(); }
    public function update(int $id,array $data): void { unset($data['responsavel_usuario_id']);$data['id']=$id;$stmt=$this->connection->prepare('UPDATE empresas SET razao_social=:razao_social,nome_fantasia=:nome_fantasia,documento=:documento,tipo_pessoa=:tipo_pessoa,segmento=:segmento,contato=:contato,telefone=:telefone,email=:email,inscricao_estadual=:inscricao_estadual,inscricao_municipal=:inscricao_municipal,endereco_logradouro=:endereco_logradouro,endereco_numero=:endereco_numero,endereco_complemento=:endereco_complemento,endereco_bairro=:endereco_bairro,endereco_cidade=:endereco_cidade,endereco_uf=:endereco_uf,endereco_cep=:endereco_cep,status=:status WHERE id=:id');$stmt->execute($data); }
    public function linkSupplier(int $companyId,int $supplierId,?string $document):void{$stmt=$this->connection->prepare("INSERT INTO empresa_integracoes (empresa_id,sistema,entidade,identificador_externo,documento_externo,status,ultima_sincronizacao_em) VALUES (:empresa_id,'SO','fornecedor',:externo,:documento,'ativo',NOW())");$stmt->execute(['empresa_id'=>$companyId,'externo'=>(string)$supplierId,'documento'=>$document]);}
    public function linkUser(int $companyId,int $userId):void{$stmt=$this->connection->prepare('SELECT 1 FROM empresa_usuarios WHERE empresa_id=:empresa_id AND usuario_id=:usuario_id LIMIT 1');$stmt->execute(['empresa_id'=>$companyId,'usuario_id'=>$userId]);if($stmt->fetchColumn()===false){$stmt=$this->connection->prepare('INSERT INTO empresa_usuarios (empresa_id,usuario_id) VALUES (:empresa_id,:usuario_id)');$stmt->execute(['empresa_id'=>$companyId,'usuario_id'=>$userId]);}}
    public function activeUserExists(int $id):bool{$stmt=$this->connection->prepare("SELECT 1 FROM usuarios WHERE id=:id AND status='ativo'");$stmt->execute(['id'=>$id]);return $stmt->fetchColumn()!==false;}
    public function changeStatus(int $id,string $status):void{$stmt=$this->connection->prepare('UPDATE empresas SET status=:status WHERE id=:id');$stmt->execute(['id'=>$id,'status'=>$status]);}
    public function users(int $companyId):array{$stmt=$this->connection->prepare('SELECT u.id,u.nome,u.email,u.status FROM empresa_usuarios eu INNER JOIN usuarios u ON u.id=eu.usuario_id WHERE eu.empresa_id=:id ORDER BY u.nome');$stmt->execute(['id'=>$companyId]);return $stmt->fetchAll();}
    public function closeOpenAccesses(int $userId):void{$stmt=$this->connection->prepare('UPDATE empresa_acessos_administrativos SET encerrado_em=NOW() WHERE usuario_id=:id AND encerrado_em IS NULL');$stmt->execute(['id'=>$userId]);}
    public function openAccess(int $companyId,int $userId,?string $reason,string $ip,string $agent):int{$stmt=$this->connection->prepare('INSERT INTO empresa_acessos_administrativos (empresa_id,usuario_id,motivo,ip,user_agent,iniciado_em) VALUES (:empresa,:usuario,:motivo,:ip,:agent,NOW())');$stmt->execute(['empresa'=>$companyId,'usuario'=>$userId,'motivo'=>$reason,'ip'=>$ip,'agent'=>$agent]);return (int)$this->connection->lastInsertId();}
    public function closeAccess(int $id):void{$stmt=$this->connection->prepare('UPDATE empresa_acessos_administrativos SET encerrado_em=COALESCE(encerrado_em,NOW()) WHERE id=:id');$stmt->execute(['id'=>$id]);}
    private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&0x0f)|0x40);$b[8]=chr((ord($b[8])&0x3f)|0x80);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
