<?php
declare(strict_types=1);
use Sigesp\Core\View;

$title = (string) $page['title'];
$pageId = 'relatorios';
$records = array_slice((array) $page['records'], 0, 8);
$columns = (array) $page['columns'];
?>
<?php View::component('page-header',['eyebrow'=>'Inteligência de dados · Demonstração','heading'=>'Central de relatórios','description'=>'Cruze indicadores esportivos e prepare apresentações institucionais.','actionLabel'=>'Gerar relatório','actionHref'=>'#','secondaryLabel'=>'Imprimir','secondaryMessage'=>'Use o botão Imprimir na área de resultados.']); ?>
<?php ob_start(); ?>
<form class="filter-form" data-demo-filter data-filter-target="#report-results"><label class="field">Período<input type="month" value="2026-08"></label><label class="field">Modalidade<select><option>Todas</option><option>Futsal</option><option>Voleibol</option><option>Atletismo</option></select></label><label class="field">Situação<select><option>Todos os atletas</option><option>Ativos</option><option>Inativos</option></select></label><label class="field">Bairro<select><option>Todos</option><option>Centro</option><option>São José</option><option>Nova Esperança</option></select></label><div><button class="button" type="submit">Aplicar</button></div></form>
<?php $filterContent = (string) ob_get_clean(); View::component('filter-bar',['filters'=>$filterContent]); ?>
<section class="stats-grid"><?php foreach ((array)$page['stats'] as $index=>$stat) View::component('stats-card',['icon'=>$stat['icon']??['◉','✓','★','%'][$index%4],'label'=>$stat['label'],'value'=>$stat['value'],'detail'=>$stat['detail']??'Consolidado demonstrativo']); ?></section>
<section class="dashboard-grid">
    <article class="surface"><div class="surface__header"><div><h2>Atletas por modalidade</h2><p>Distribuição da amostra consolidada.</p></div></div><div class="demo-chart"><?php foreach ([['Futsal',342],['Voleibol',286],['Atletismo',214],['Natação',176],['Basquete',128]] as [$label,$value]): ?><div class="demo-chart__row"><span><?= View::e($label) ?></span><span class="demo-chart__track"><i class="demo-chart__bar" style="width:<?= (int)round($value/342*100) ?>%"></i></span><strong><?= $value ?></strong></div><?php endforeach; ?></div></article>
    <article class="surface"><div class="surface__header"><div><h2>Resumo documental</h2><p>Situação da base demonstrativa.</p></div></div><div class="metric-grid"><div class="metric"><small>Regulares</small><strong>1.183</strong><span><i class="status-dot"></i>94,8%</span></div><div class="metric"><small>Pendentes</small><strong>47</strong><span><i class="status-dot status-dot--warning"></i>3,8%</span></div><div class="metric"><small>Vencidos</small><strong>18</strong><span><i class="status-dot status-dot--danger"></i>1,4%</span></div></div></article>
    <article class="surface dashboard-wide" id="report-results"><div class="demo-toolbar"><div><h2>Resultado consolidado</h2><p class="demo-toolbar__summary">Dados fictícios para apresentação.</p></div><div class="demo-toolbar__actions"><button class="button button--secondary" type="button" data-demo-action="csv">CSV</button><button class="button button--secondary" type="button" data-demo-action="export">Excel</button><button class="button button--secondary" type="button" data-demo-action="export">PDF</button><button class="button" type="button" data-demo-action="print">Imprimir</button></div></div><div class="data-table"><table><thead><tr><?php foreach($columns as $label): ?><th scope="col"><?= View::e((string)$label) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($records as $record): ?><tr data-demo-record><?php foreach($columns as $key=>$label): ?><td><?= View::e((string)($record[$key]??'—')) ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><section class="record-cards" aria-label="Relatórios em cartões"><?php foreach($records as $record): ?><article class="record-card" data-demo-record><div class="record-card__head"><span class="avatar">▥</span><div><strong><?= View::e((string)($record['nome']??'Relatório')) ?></strong><small><?= View::e((string)($record['periodo']??'Período demonstrativo')) ?> · <?= View::e((string)($record['registros']??0)) ?> registros</small></div><?php View::component('badge',['label'=>(string)($record['status']??'Disponível'),'tone'=>'success']); ?></div></article><?php endforeach; ?></section></article>
</section>
