-- Tabela de Secretarias
CREATE TABLE IF NOT EXISTS secretarias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    codigo_acesso VARCHAR(100) UNIQUE NOT NULL, -- Código para login da secretaria
    cor_relatorio VARCHAR(7) DEFAULT '#D9E3F4',
    responsavel VARCHAR(255),
    email VARCHAR(255),
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Fornecedores
CREATE TABLE IF NOT EXISTS fornecedores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) UNIQUE,
    contato VARCHAR(255),
    telefone VARCHAR(20),
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Usuários (Internos: Prefeitura/Suporte/Funcionario)
CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    usuario VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    nivel ENUM('ADMIN', 'SUPORTE', 'SECRETARIO', 'CASA_CIVIL', 'SEFAZ', 'FUNCIONARIO') NOT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oficios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(50) UNIQUE NOT NULL, -- Ex: OF-2026-0001
    secretaria_id INT NOT NULL,
    local VARCHAR(150) DEFAULT NULL,
    justificativa TEXT,
    resumo_itens TEXT DEFAULT NULL,
    status ENUM('PENDENTE_ITENS', 'ENVIADO', 'EM_ANALISE', 'APROVADO', 'REPROVADO', 'ARQUIVADO') DEFAULT 'PENDENTE_ITENS',
    usuario_id INT NOT NULL, -- Quem cadastrou
    arquivo_orcamento VARCHAR(255) DEFAULT NULL,
    arquivo_oficio VARCHAR(255) DEFAULT NULL,
    valor_orcamento DECIMAL(15,2) NULL DEFAULT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (secretaria_id) REFERENCES secretarias(id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Anexos do Ofício (orçamentos, fotos, scans e ofícios)
CREATE TABLE IF NOT EXISTS oficio_anexos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    oficio_id INT NOT NULL,
    caminho VARCHAR(255) NOT NULL,
    tipo ENUM('ORCAMENTO', 'OFICIO') NOT NULL,
    nome_original VARCHAR(255),
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (oficio_id) REFERENCES oficios(id) ON DELETE CASCADE
);

-- Itens do Ofício
CREATE TABLE IF NOT EXISTS itens_oficio (
    id INT AUTO_INCREMENT PRIMARY KEY,
    oficio_id INT NOT NULL,
    produto VARCHAR(255) NOT NULL,
    quantidade DECIMAL(10,2) NOT NULL,
    unidade VARCHAR(20) DEFAULT 'UN',
    valor_unitario DECIMAL(15,2) NULL DEFAULT 0.00,
    FOREIGN KEY (oficio_id) REFERENCES oficios(id) ON DELETE CASCADE
);

-- Tabela de Aquisições
CREATE TABLE IF NOT EXISTS aquisicoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero_aq VARCHAR(50) UNIQUE NOT NULL, -- Ex: AQ-2026-0001
    codigo_entrega VARCHAR(50) UNIQUE NOT NULL, -- Ex: ENT-2026-AB12C
    oficio_id INT NOT NULL,
    fornecedor_id INT NOT NULL,
    valor_total DECIMAL(15,2) DEFAULT 0,
    responsavel_entrega VARCHAR(255),
    status ENUM('AGUARDANDO ENTREGA', 'FINALIZADO') DEFAULT 'AGUARDANDO ENTREGA',
    data_finalizacao DATETIME,
    usuario_id_finalizou INT,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (oficio_id) REFERENCES oficios(id),
    FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    FOREIGN KEY (usuario_id_finalizou) REFERENCES usuarios(id)
);

-- Itens da Aquisição (Pode herdar do ofício, mas permite ajuste de valor)
CREATE TABLE IF NOT EXISTS itens_aquisicao (
    id INT AUTO_INCREMENT PRIMARY KEY,
    aquisicao_id INT NOT NULL,
    oficio_item_id INT NULL,
    produto VARCHAR(255) NOT NULL,
    quantidade DECIMAL(10,2) NOT NULL,
    valor_unitario DECIMAL(15,2) NOT NULL,
    INDEX idx_itens_aquisicao_oficio_item (oficio_item_id),
    FOREIGN KEY (aquisicao_id) REFERENCES aquisicoes(id) ON DELETE CASCADE
);

-- Logs do Sistema
CREATE TABLE IF NOT EXISTS logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT,
    secretaria_id INT,
    acao VARCHAR(100) NOT NULL,
    detalhes TEXT,
    ip VARCHAR(45),
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Dados Iniciais
INSERT INTO secretarias (nome, codigo_acesso, cor_relatorio, responsavel) VALUES
('COMIÇÃO DE CONTRATAÇÃO DE COARI-CCC', 'CCC2026', '#D9E3F4', NULL),
('CONTROLADORIA GERAL DO MUNICICÍPIO - CGM', 'CGM2026', '#E2F0D9', NULL),
('COORDENADORIA REGIONAL DE EDUCAÇÃO DE COARI', 'CREC2026', '#FCE4D6', NULL),
('PROCURADORIA GERAL DO MUNICÍPIO - PGM', 'PGM2026', '#FFF2CC', NULL),
('SECRETARIA DE ESTADO DA EDUCAÇÃO E DESPORTO ESCOLAR COORDENADORIA REGIONAL DE EDUCAÇÃO DE COARI-SEDUC', 'SEDUC2026', '#EADCF8', NULL),
('SECRETARIA MUNICIPAL DA CASA CIVIL - SMCC', 'SMCC2026', '#C9DAF8', NULL),
('SECRETARIA MUNICIPAL DE ADMINISTRAÇÃO - SEMAD', 'SEMAD2026', '#D9EAD3', NULL),
('SECRETARIA MUNICIPAL DE ASSISTÊNCIA SOCIAL - SEMAS', 'SEMAS2026', '#F4CCCC', NULL),
('SECRETARIA MUNICIPAL DE CIÊNCIA, TECNOLOGIA E INOVAÇÃO', 'SMCTI2026', '#D0E0E3', NULL),
('SECRETARIA MUNICIPAL DE COMUNICAÇÃO - SEMCOM', 'SEMCOM2026', '#FCE5CD', NULL),
('SECRETARIA MUNICIPAL DE CULTURA E TURISMO - SECULT', 'SECULT2026', '#D5A6BD', NULL),
('SECRETARIA MUNICIPAL DE DESENVOLVIMENTO RURAL E ECONÔMICO - SMDRE', 'SMDRE2026', '#B6D7A8', NULL),
('SECRETARIA MUNICIPAL DE EDUCAÇÃO - SEMED', 'SEMED2026', '#A4C2F4', NULL),
('SECRETARIA MUNICIPAL DE ESPORTE - SEMESP', 'SEMESP2026', '#B4A7D6', NULL),
('SECRETARIA MUNICIPAL DE FAZENDA - SEMFAZ', 'SEMFAZ2026', '#FFD966', NULL),
('SECRETARIA MUNICIPAL DE INDÚSTRIA E COMERCIO - SEMIC', 'SEC2026', '#CFE2F3', NULL),
('SECRETARIA MUNICIPAL DE LIMPEZA PÚBLICA - SEMLIP', 'SEMLIP2026', '#D9D2E9', NULL),
('SECRETARIA MUNICIPAL DE MEIO AMBIENTE - SEMMA', 'SEMMA2026', '#B7E1CD', NULL),
('SECRETARIA MUNICIPAL DE OBRAS - SEMOB', 'SEMOB2026', '#F9CB9C', NULL),
('SECRETARIA MUNICIPAL DE PLANEJAMENTO - SEMPLAN', 'SEMPLAN2026', '#CFE2F3', NULL),
('SECRETARIA MUNICIPAL DE SAÚDE - SEMSA', 'SEMSA2026', '#EA9999', NULL),
('SECRETARIA MUNICIPAL DE SEGURANÇA PÚBLICA E DEFESA SOCIAL - AEROPORTO', 'AEROPORTO2026', '#B7B7B7', NULL),
('SECRETARIA MUNICIPAL DE SEGURANÇA PÚBLICA E DEFESA SOCIAL - SMSPDS', 'SMSPDS2026', '#A2C4C9', NULL),
('SECRETARIA MUNICIPAL DE TERRAS E HABITAÇÃO - SEMTH', 'SEMTH2026', '#D5E8D4', NULL),
('SECRETARIA MUNICIPAL EXTRAORDINÁRIA', 'SME2026', '#E6B8AF', NULL),
('SECRETÁRIO MUNICIPAL DE RELAÇÕES INSTITUCIONAIS', 'SMRI2026', '#D9D9D9', NULL);

INSERT INTO fornecedores (nome, cnpj, contato) VALUES 
('Papelaria Central', '12.345.678/0001-01', 'João Papel'),
('Supermercado Silva', '22.333.444/0001-02', 'Sr. Silva'),
('Construtora Rocha', '33.444.555/0001-03', 'Ricardo Rocha');

-- Senhas padrão: '123'
-- Hash gerado por password_hash('123', PASSWORD_DEFAULT)
INSERT INTO usuarios (nome, usuario, senha, nivel) VALUES 
('Suporte Técnico', 'suporte', '$2y$10$0Aw4ie.N1y1atk5dLMohYOVQGOKS04fQK95ggn6HN2AGMhvGqbv2O', 'SUPORTE'),
('Prefeito Administrativo', 'admin', '$2y$10$0Aw4ie.N1y1atk5dLMohYOVQGOKS04fQK95ggn6HN2AGMhvGqbv2O', 'ADMIN'),
('Recepcionista Central', 'func', '$2y$10$0Aw4ie.N1y1atk5dLMohYOVQGOKS04fQK95ggn6HN2AGMhvGqbv2O', 'FUNCIONARIO');
