<?php

declare(strict_types=1);

use App\Core\Database; use App\Core\Logger; use App\Repositories\AccessLevelRepository; use App\Repositories\AuditLogRepository; use App\Repositories\ComidaMesaRepository; use App\Repositories\PermissionRepository; use App\Repositories\UserRepository; use App\Repositories\UserSessionRepository; use App\Services\AuditService; use App\Services\AuthService; use App\Services\AuthorizationService; use App\Services\ComidaMesaDocumentService; use App\Services\PermissionService;

require_once dirname(__DIR__, 2) . '/bootstrap.php';
header('Cache-Control: private, no-store');
function cm_forbid(int $status): never { http_response_code($status); header('Content-Type: application/json; charset=utf-8'); echo json_encode(['ok' => false, 'error' => $status === 403 ? 'Acesso negado.' : 'Documento não encontrado.'], JSON_UNESCAPED_UNICODE); exit; }
try { if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'GET') { header('Allow: GET'); cm_forbid(404); } $pdo = Database::connection(); $levels = new AccessLevelRepository($pdo); $audit = new AuditService(new AuditLogRepository($pdo)); $auth = new AuthService(new UserRepository($pdo), new UserSessionRepository($pdo), $levels, $audit); $user = $auth->currentUser(); if ($user === null) cm_forbid(403); $authorization = new AuthorizationService(new PermissionService(new PermissionRepository($pdo)), $levels); if (!$authorization->can($user, 'comida_mesa.documentos_visualizar')) cm_forbid(403); $id = isset($_GET['id']) && preg_match('/^\d+$/', (string) $_GET['id']) === 1 ? (int) $_GET['id'] : 0; $document = (new ComidaMesaDocumentService(new ComidaMesaRepository($pdo)))->resolveForView($id); $path = (string) $document['absolute_path']; header('Content-Type: ' . (string) $document['mime_type']); header('Content-Length: ' . (string) filesize($path)); header('X-Content-Type-Options: nosniff'); header('Content-Disposition: inline; filename="' . addcslashes((string) $document['nome_original'], "\"\\") . '"'); readfile($path); exit; } catch (RuntimeException $exception) { cm_forbid($exception->getCode() === 403 ? 403 : 404); } catch (Throwable $exception) { Logger::application('Comida Mesa document view failed.', ['type' => $exception::class, 'code' => $exception->getCode()]); cm_forbid(404); }
