CREATE TABLE categorias_lavagem_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_cnpj VARCHAR(20) NOT NULL,
  nome VARCHAR(120) NOT NULL,
  descricao TEXT DEFAULT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE empresas_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cnpj VARCHAR(20) NOT NULL,
  nome_fantasia VARCHAR(150) NOT NULL,
  razao_social VARCHAR(200) DEFAULT NULL,
  telefone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  endereco TEXT DEFAULT NULL,
  cidade VARCHAR(100) DEFAULT NULL,
  estado CHAR(2) DEFAULT NULL,
  cep VARCHAR(10) DEFAULT NULL,
  status ENUM('ativa', 'inativa', 'suspensa') NOT NULL DEFAULT 'ativa',
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lavadores_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_cnpj VARCHAR(20) NOT NULL,
  nome VARCHAR(150) NOT NULL,
  cpf VARCHAR(20) DEFAULT NULL,
  telefone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lavagens_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_cnpj VARCHAR(20) NOT NULL,
  lavador_cpf VARCHAR(20) NOT NULL,
  placa VARCHAR(10) DEFAULT NULL,
  modelo VARCHAR(120) DEFAULT NULL,
  cor VARCHAR(30) DEFAULT NULL,
  categoria_id BIGINT(20) UNSIGNED DEFAULT NULL,
  categoria_nome VARCHAR(120) DEFAULT NULL,
  valor DECIMAL(12,2) NOT NULL,
  forma_pagamento VARCHAR(40) DEFAULT 'dinheiro',
  status ENUM('aberta', 'concluida', 'cancelada') NOT NULL DEFAULT 'aberta',
  checkin_at DATETIME DEFAULT NULL,
  checkout_at DATETIME DEFAULT NULL,
  observacoes TEXT DEFAULT NULL,
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lavagem_adicionais_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lavagem_id BIGINT(20) UNSIGNED NOT NULL,
  adicional_id BIGINT(20) UNSIGNED DEFAULT NULL,
  nome VARCHAR(120) NOT NULL,
  valor DECIMAL(12,2) NOT NULL,
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lavagem_id) REFERENCES lavagens_peca(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE solicitacoes_empresas_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome_fantasia VARCHAR(150) NOT NULL,
  cnpj VARCHAR(20) DEFAULT NULL,
  telefone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  proprietario_nome VARCHAR(150) NOT NULL,
  proprietario_email VARCHAR(150) NOT NULL,
  proprietario_senha_hash VARCHAR(255) DEFAULT NULL,
  status ENUM('pendente', 'aprovada', 'recusada') NOT NULL DEFAULT 'pendente',
  token_aprovacao VARCHAR(64) DEFAULT NULL,
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE usuarios_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_cnpj VARCHAR(20) DEFAULT NULL,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL,
  cpf VARCHAR(20) DEFAULT NULL,
  telefone VARCHAR(20) DEFAULT NULL,
  senha VARCHAR(255) NOT NULL,
  perfil ENUM('super_admin', 'dono', 'funcionario') NOT NULL DEFAULT 'funcionario',
  tipo_funcionario ENUM(
    'lavajato',
    'autopeca',
    'administrativo',
    'caixa',
    'estoque'
  ) DEFAULT 'lavajato',
  status TINYINT(1) NOT NULL DEFAULT 1,
  precisa_redefinir_senha TINYINT(1) NOT NULL DEFAULT 0,
  senha_atualizada_em DATETIME DEFAULT NULL,
  ultimo_login_em DATETIME DEFAULT NULL,
  falhas_login INT(10) UNSIGNED NOT NULL DEFAULT 0,
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE usuarios_redefinicao_senha_peca (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT(20) UNSIGNED DEFAULT NULL,
  email VARCHAR(150) NOT NULL,
  token VARCHAR(64) NOT NULL,
  otp VARCHAR(6) DEFAULT NULL,
  expiracao DATETIME NOT NULL,
  usado_em DATETIME DEFAULT NULL,
  ip_solicitante VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE vales_lavadores_peca (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  empresa_cnpj VARCHAR(20) NOT NULL,
  lavador_id BIGINT UNSIGNED NOT NULL,
  lavador_nome VARCHAR(150) NOT NULL,
  valor DECIMAL(12,2) NOT NULL,
  motivo VARCHAR(255) DEFAULT NULL,
  criado_por_cpf VARCHAR(20) DEFAULT NULL,
  forma_pagamento VARCHAR(40) DEFAULT 'dinheiro',
  criado_em TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_empresa (empresa_cnpj),
  KEY idx_lavador (lavador_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;