CREATE TABLE IF NOT EXISTS clientes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(20) NULL,
    tipo_pessoa ENUM('fisica', 'juridica') NOT NULL DEFAULT 'fisica',
    nome VARCHAR(150) NOT NULL,
    documento VARCHAR(20) NULL,
    telefone VARCHAR(30) NULL,
    whatsapp VARCHAR(30) NULL,
    email VARCHAR(150) NULL,
    endereco VARCHAR(150) NULL,
    numero VARCHAR(30) NULL,
    complemento VARCHAR(100) NULL,
    bairro VARCHAR(100) NULL,
    cidade VARCHAR(100) NULL,
    uf CHAR(2) NULL,
    cep VARCHAR(10) NULL,
    observacoes TEXT NULL,
    status ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_clientes_codigo (codigo),
    UNIQUE KEY uk_clientes_documento (documento),
    KEY idx_clientes_nome (nome),
    KEY idx_clientes_tipo_pessoa (tipo_pessoa),
    KEY idx_clientes_cidade (cidade),
    KEY idx_clientes_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orcamentos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(20) NULL,
    cliente_id INT UNSIGNED NOT NULL,
    responsavel_id INT UNSIGNED NULL,
    data_emissao DATE NOT NULL,
    validade DATE NOT NULL,
    status ENUM('rascunho', 'enviado', 'aguardando_aprovacao', 'aprovado', 'recusado') NOT NULL DEFAULT 'rascunho',
    observacoes TEXT NULL,
    motivo_recusa TEXT NULL,
    subtotal_servicos DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    subtotal_produtos DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    subtotal_outros DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    desconto DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    acrescimo DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    aprovado_em DATETIME NULL,
    recusado_em DATETIME NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_orcamentos_numero (numero),
    KEY idx_orcamentos_cliente (cliente_id),
    KEY idx_orcamentos_responsavel (responsavel_id),
    KEY idx_orcamentos_emissao (data_emissao),
    KEY idx_orcamentos_validade (validade),
    KEY idx_orcamentos_status (status),
    CONSTRAINT fk_orcamentos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_orcamentos_responsavel FOREIGN KEY (responsavel_id) REFERENCES funcionarios(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orcamento_itens (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    orcamento_id INT UNSIGNED NOT NULL,
    tipo ENUM('servico', 'produto', 'outro') NOT NULL,
    referencia_id INT UNSIGNED NULL,
    descricao VARCHAR(255) NOT NULL,
    unidade VARCHAR(20) NOT NULL DEFAULT 'un',
    quantidade DECIMAL(12,3) NOT NULL DEFAULT 1.000,
    valor_unitario DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    desconto DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ordem INT UNSIGNED NOT NULL DEFAULT 0,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_orcamento_itens_orcamento (orcamento_id),
    KEY idx_orcamento_itens_tipo (tipo),
    KEY idx_orcamento_itens_referencia (referencia_id),
    KEY idx_orcamento_itens_ordem (ordem),
    CONSTRAINT fk_orcamento_itens_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamentos(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
