<?php
use Sigesp\Core\View;
$title = 'Visão geral'; $pageId = 'dashboard';
$today = (new DateTimeImmutable('today'))->format('d/m/Y');
?>
<?php View::component('page-header', ['eyebrow' => 'Painel institucional · ' . $today, 'heading' => 'Olá, ' . explode(' ', (string) (\Sigesp\Core\Auth::user()['nome'] ?? 'gestor'))[0], 'description' => 'Acompanhe os principais indicadores da gestão esportiva municipal.', 'actionLabel' => 'Cadastrar atleta', 'actionHref' => '/atletas/novo', 'secondaryLabel' => 'Gerar relatório']); ?>
<section class="stats-grid"><?php
$cards = [['◉', 'Atletas cadastrados', $stats['total'], 'Base consolidada'], ['✓', 'Atletas ativos', $stats['ativos'], 'Com cadastro ativo'], ['▣', 'Documentos pendentes', $stats['pendentes'], 'Requerem acompanhamento'], ['◌', 'Modalidades ativas', $stats['modalidades'], 'Em funcionamento']];
foreach ($cards as [$icon, $label, $value, $detail]) View::component('stats-card', compact('icon', 'label', 'value', 'detail'));
?></section>
<section class="dashboard-grid"><article class="surface"><div class="surface__header"><div><h2>Atletas por modalidade</h2><p>Vínculos ativos registrados no sistema.</p></div><a href="<?= View::e(View::url('/modalidades')) ?>">Ver modalidades</a></div><div class="chart-wrap"><canvas data-modalidades-chart data-modalidades-chart='<?= View::e(json_encode($chart, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT)) ?>' aria-label="Gráfico de atletas por modalidade"></canvas></div></article><aside class="surface"><div class="surface__header"><div><h2>Alertas operacionais</h2><p>Itens que merecem atenção.</p></div></div><div class="mini-list"><div class="mini-list__item"><span class="avatar">!</span><div><strong>Documentos pendentes</strong><small><?= $stats['pendentes'] ?> registro(s) aguardando acompanhamento</small></div><a href="<?= View::e(View::url('/documentos')) ?>">Ver</a></div><div class="mini-list__item"><span class="avatar">+</span><div><strong>Novo cadastro</strong><small>Inclua atletas com dados completos</small></div><a href="<?= View::e(View::url('/atletas/novo')) ?>">Abrir</a></div><div class="mini-list__item"><span class="avatar">▥</span><div><strong>Relatórios</strong><small>Consulte dados consolidados</small></div><a href="<?= View::e(View::url('/relatorios')) ?>">Acessar</a></div></div></aside><article class="surface dashboard-wide"><div class="surface__header"><div><h2>Atalhos da operação</h2><p>Acesse rapidamente os fluxos mais utilizados.</p></div></div><?php View::component('quick-actions', ['actions' => [['href'=>'/atletas','icon'=>'◉','label'=>'Consultar atletas'],['href'=>'/frequencias','icon'=>'✓','label'=>'Registrar frequência'],['href'=>'/eventos','icon'=>'★','label'=>'Ver eventos'],['href'=>'/documentos','icon'=>'▣','label'=>'Analisar documentos']]]); ?></article></section>
