-- Catalogo inicial de permissoes do sistema.
-- Seguro para reexecucao: codigo e unico e os dados sao atualizados sem duplicar.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO permissoes
    (grupo, modulo, codigo, nome, descricao, ordem)
VALUES
    ('Dashboard', 'dashboard', 'dashboard.visualizar', 'Visualizar dashboard', 'Permite acessar a visão geral do sistema.', 10),
    ('Dashboard', 'dashboard', 'dashboard.visualizar_operacional', 'Visualizar dashboard operacional', 'Permite acessar indicadores operacionais do dashboard.', 20),
    ('Dashboard', 'dashboard', 'dashboard.visualizar_financeiro', 'Visualizar dashboard financeiro', 'Permite acessar indicadores financeiros do dashboard.', 30),

    ('Clientes', 'cliente', 'cliente.visualizar', 'Visualizar clientes', 'Permite acessar a listagem e os dados dos clientes.', 110),
    ('Clientes', 'cliente', 'cliente.criar', 'Criar clientes', 'Permite cadastrar novos clientes.', 120),
    ('Clientes', 'cliente', 'cliente.importar', 'Importar clientes', 'Permite importar clientes em lote a partir do relatório PDF do A7.', 125),
    ('Clientes', 'cliente', 'cliente.editar', 'Editar clientes', 'Permite alterar dados cadastrais de clientes.', 130),
    ('Clientes', 'cliente', 'cliente.desativar', 'Desativar clientes', 'Permite desativar clientes sem excluir o cadastro.', 140),
    ('Clientes', 'cliente', 'cliente.excluir', 'Excluir clientes', 'Permite excluir cadastros de clientes.', 150),
    ('Clientes', 'cliente', 'cliente.visualizar_historico', 'Visualizar histórico de clientes', 'Permite consultar histórico de atendimentos dos clientes.', 160),

    ('Ordens de Serviço', 'os', 'os.visualizar', 'Visualizar ordens de serviço', 'Permite acessar ordens de serviço.', 210),
    ('Ordens de Serviço', 'os', 'os.criar', 'Criar ordens de serviço', 'Permite cadastrar novas ordens de serviço.', 220),
    ('Ordens de Serviço', 'os', 'os.editar', 'Editar ordens de serviço', 'Permite alterar ordens de serviço existentes.', 230),
    ('Ordens de Serviço', 'os', 'os.agendar', 'Agendar ordens de serviço', 'Permite definir data e horário de atendimento.', 240),
    ('Ordens de Serviço', 'os', 'os.alterar_equipe', 'Alterar equipe da OS', 'Permite alterar instalador e ajudante da ordem de serviço.', 250),
    ('Ordens de Serviço', 'os', 'os.alterar_status', 'Alterar status da OS', 'Permite mudar o status operacional da ordem de serviço.', 260),
    ('Ordens de Serviço', 'os', 'os.cancelar', 'Cancelar ordens de serviço', 'Permite cancelar ordens de serviço.', 270),
    ('Ordens de Serviço', 'os', 'os.finalizar', 'Finalizar ordens de serviço', 'Permite concluir ordens de serviço.', 280),
    ('Ordens de Serviço', 'os', 'os.reabrir', 'Reabrir ordens de serviço', 'Permite reabrir ordens de serviço concluídas ou canceladas.', 290),
    ('Ordens de Serviço', 'os', 'os.imprimir', 'Imprimir ordens de serviço', 'Permite imprimir ordens de serviço.', 300),
    ('Ordens de Serviço', 'os', 'os.estornar', 'Estornar ordens de serviço', 'Permite desfazer a finalização compensando estoque, caixa, pagamentos e contas a receber.', 305),
    ('Ordens de Serviço', 'os', 'os.excluir', 'Excluir ordens de serviço', 'Permite excluir ordens de serviço.', 310),
    ('Ordens de Serviço', 'os', 'os.visualizar_valores', 'Visualizar valores da OS', 'Permite visualizar valores financeiros da ordem de serviço.', 320),
    ('Ordens de Serviço', 'os', 'os.emitir_comprovante', 'Emitir comprovante de OS', 'Permite emitir comprovante não fiscal de serviço.', 330),
    ('Ordens de Serviço', 'os', 'os.finalizar_com_pagamento', 'Finalizar OS com pagamento', 'Permite finalizar OS registrando pagamento e saldo pendente.', 340),

    ('Orçamentos', 'orcamento', 'orcamento.visualizar', 'Visualizar orçamentos', 'Permite acessar orçamentos.', 410),
    ('Orçamentos', 'orcamento', 'orcamento.criar', 'Criar orçamentos', 'Permite cadastrar novos orçamentos.', 420),
    ('Orçamentos', 'orcamento', 'orcamento.editar', 'Editar orçamentos', 'Permite alterar orçamentos existentes.', 430),
    ('Orçamentos', 'orcamento', 'orcamento.aprovar', 'Aprovar orçamentos', 'Permite registrar aprovação de orçamentos.', 440),
    ('Orçamentos', 'orcamento', 'orcamento.recusar', 'Recusar orçamentos', 'Permite registrar recusa de orçamentos.', 450),
    ('Orçamentos', 'orcamento', 'orcamento.converter_os', 'Converter orçamento em OS', 'Permite converter orçamento aprovado em ordem de serviço.', 460),
    ('Orçamentos', 'orcamento', 'orcamento.imprimir', 'Imprimir orçamentos', 'Permite imprimir orçamentos.', 470),
    ('Orçamentos', 'orcamento', 'orcamento.excluir', 'Excluir orçamentos', 'Permite excluir orçamentos.', 480),

    ('Agenda', 'agenda', 'agenda.visualizar', 'Visualizar agenda', 'Permite acessar a agenda de atendimentos.', 510),
    ('Agenda', 'agenda', 'agenda.criar', 'Criar agendamentos', 'Permite criar compromissos na agenda.', 520),
    ('Agenda', 'agenda', 'agenda.editar', 'Editar agendamentos', 'Permite alterar compromissos da agenda.', 530),
    ('Agenda', 'agenda', 'agenda.reagendar', 'Reagendar atendimentos', 'Permite alterar data ou horário de atendimentos.', 540),
    ('Agenda', 'agenda', 'agenda.cancelar', 'Cancelar agendamentos', 'Permite cancelar compromissos da agenda.', 550),
    ('Agenda', 'agenda', 'agenda.alterar_dupla', 'Alterar dupla da agenda', 'Permite alterar a dupla responsável pelo atendimento.', 560),
    ('Agenda', 'agenda', 'agenda.criar_lembrete', 'Criar lembretes', 'Permite criar lembretes na agenda.', 570),

    ('Serviços da Semana', 'painel_semanal', 'painel_semanal.visualizar', 'Visualizar serviços da semana', 'Permite acessar o painel semanal de serviços.', 610),
    ('Serviços da Semana', 'painel_semanal', 'painel_semanal.adicionar', 'Adicionar serviço semanal', 'Permite adicionar serviços ao painel semanal.', 620),
    ('Serviços da Semana', 'painel_semanal', 'painel_semanal.editar', 'Editar serviço semanal', 'Permite alterar serviços do painel semanal.', 630),
    ('Serviços da Semana', 'painel_semanal', 'painel_semanal.alterar_dupla', 'Alterar dupla semanal', 'Permite alterar a dupla no painel semanal.', 640),
    ('Serviços da Semana', 'painel_semanal', 'painel_semanal.alterar_horario', 'Alterar horário semanal', 'Permite alterar horários no painel semanal.', 650),
    ('Serviços da Semana', 'painel_semanal', 'painel_semanal.alterar_status', 'Alterar status semanal', 'Permite alterar status no painel semanal.', 660),
    ('Serviços da Semana', 'painel_semanal', 'painel_semanal.cancelar', 'Cancelar serviço semanal', 'Permite cancelar serviços do painel semanal.', 670),

    ('Produtos', 'produto', 'produto.visualizar', 'Visualizar produtos', 'Permite acessar produtos e peças.', 710),
    ('Produtos', 'produto', 'produto.visualizar_preco_venda', 'Visualizar preço de venda', 'Permite visualizar preço de venda dos produtos.', 720),
    ('Produtos', 'produto', 'produto.visualizar_preco_custo', 'Visualizar preço de custo', 'Permite visualizar preço de custo dos produtos.', 730),
    ('Produtos', 'produto', 'produto.criar', 'Criar produtos', 'Permite cadastrar produtos e peças.', 740),
    ('Produtos', 'produto', 'produto.editar', 'Editar produtos', 'Permite alterar produtos e peças.', 750),
    ('Produtos', 'produto', 'produto.excluir', 'Excluir produtos', 'Permite excluir produtos e peças.', 760),

    ('Estoque', 'estoque', 'estoque.visualizar', 'Visualizar estoque', 'Permite acessar saldos de estoque.', 810),
    ('Estoque', 'estoque', 'estoque.entrada', 'Registrar entrada de estoque', 'Permite registrar entradas de estoque.', 820),
    ('Estoque', 'estoque', 'estoque.saida', 'Registrar saída de estoque', 'Permite registrar saídas de estoque.', 830),
    ('Estoque', 'estoque', 'estoque.ajustar', 'Ajustar estoque', 'Permite realizar ajustes manuais de estoque.', 840),
    ('Estoque', 'estoque', 'estoque.visualizar_historico', 'Visualizar histórico de estoque', 'Permite consultar movimentações de estoque.', 850),
    ('Estoque', 'estoque', 'estoque.autorizar_saldo_negativo', 'Autorizar saldo negativo', 'Permite autorizar baixa de produto acima do saldo disponível.', 860),

    ('Serviços', 'servico', 'servico.visualizar', 'Visualizar serviços', 'Permite acessar serviços cadastrados.', 910),
    ('Serviços', 'servico', 'servico.criar', 'Criar serviços', 'Permite cadastrar serviços.', 920),
    ('Serviços', 'servico', 'servico.editar', 'Editar serviços', 'Permite alterar serviços cadastrados.', 930),
    ('Serviços', 'servico', 'servico.excluir', 'Excluir serviços', 'Permite excluir serviços cadastrados.', 940),
    ('Serviços', 'servico', 'servico.alterar_preco', 'Alterar preço de serviço', 'Permite alterar preços de serviços cadastrados.', 950),

    ('Funcionários', 'funcionario', 'funcionario.visualizar', 'Visualizar funcionários', 'Permite acessar funcionários.', 1010),
    ('Funcionários', 'funcionario', 'funcionario.criar', 'Criar funcionários', 'Permite cadastrar funcionários.', 1020),
    ('Funcionários', 'funcionario', 'funcionario.editar', 'Editar funcionários', 'Permite alterar dados de funcionários.', 1030),
    ('Funcionários', 'funcionario', 'funcionario.visualizar_salario', 'Visualizar salário', 'Permite visualizar salário de funcionários.', 1040),
    ('Funcionários', 'funcionario', 'funcionario.editar_salario', 'Editar salário', 'Permite alterar salário de funcionários.', 1050),
    ('Funcionários', 'funcionario', 'funcionario.visualizar_documentos', 'Visualizar documentos', 'Permite visualizar documentos de funcionários.', 1060),
    ('Funcionários', 'funcionario', 'funcionario.editar_documentos', 'Editar documentos', 'Permite alterar documentos de funcionários.', 1070),
    ('Funcionários', 'funcionario', 'funcionario.visualizar_dados_bancarios', 'Visualizar dados bancários', 'Permite visualizar dados bancários de funcionários.', 1080),
    ('Funcionários', 'funcionario', 'funcionario.editar_dados_bancarios', 'Editar dados bancários', 'Permite alterar dados bancários de funcionários.', 1090),

    ('Fornecedores', 'fornecedor', 'fornecedor.visualizar', 'Visualizar fornecedores', 'Permite acessar fornecedores.', 1110),
    ('Fornecedores', 'fornecedor', 'fornecedor.criar', 'Criar fornecedores', 'Permite cadastrar fornecedores.', 1120),
    ('Fornecedores', 'fornecedor', 'fornecedor.editar', 'Editar fornecedores', 'Permite alterar fornecedores.', 1130),
    ('Fornecedores', 'fornecedor', 'fornecedor.desativar', 'Desativar fornecedores', 'Permite inativar ou reativar fornecedores.', 1140),

    ('Caixa', 'caixa', 'caixa.visualizar', 'Visualizar caixa', 'Permite acessar o caixa.', 1310),
    ('Caixa', 'caixa', 'caixa.abrir', 'Abrir caixa', 'Permite abrir caixa operacional.', 1320),
    ('Caixa', 'caixa', 'caixa.registrar_venda', 'Registrar venda', 'Permite registrar vendas no caixa.', 1330),
    ('Caixa', 'caixa', 'caixa.registrar_recebimento', 'Registrar recebimento', 'Permite registrar recebimentos no caixa.', 1340),
    ('Caixa', 'caixa', 'caixa.suprimento', 'Registrar suprimento', 'Permite registrar suprimentos de caixa.', 1350),
    ('Caixa', 'caixa', 'caixa.sangria', 'Registrar sangria', 'Permite registrar sangrias de caixa.', 1360),
    ('Caixa', 'caixa', 'caixa.estornar', 'Estornar caixa', 'Permite estornar movimentações de caixa.', 1370),
    ('Caixa', 'caixa', 'caixa.fechar', 'Fechar caixa', 'Permite fechar caixa operacional.', 1380),
    ('Caixa', 'caixa', 'caixa.visualizar_saldo', 'Visualizar saldo do caixa', 'Permite visualizar saldo do caixa.', 1390),

    ('Financeiro', 'financeiro', 'financeiro.visualizar', 'Visualizar financeiro', 'Permite acessar informações financeiras.', 1510),
    ('Financeiro', 'financeiro', 'financeiro.visualizar_custos', 'Visualizar custos', 'Permite visualizar custos financeiros.', 1520),
    ('Financeiro', 'financeiro', 'financeiro.visualizar_lucro', 'Visualizar lucro', 'Permite visualizar lucro financeiro.', 1530),
    ('Financeiro', 'financeiro', 'financeiro.criar_lancamento', 'Criar lançamento financeiro', 'Permite criar lançamentos financeiros.', 1540),
    ('Financeiro', 'financeiro', 'financeiro.editar_lancamento', 'Editar lançamento financeiro', 'Permite alterar lançamentos financeiros.', 1550),
    ('Financeiro', 'financeiro', 'financeiro.estornar', 'Estornar financeiro', 'Permite estornar lançamentos financeiros.', 1560),
    ('Financeiro', 'contas_pagar', 'contas_pagar.visualizar', 'Visualizar contas a pagar', 'Permite acessar a carteira de contas a pagar.', 1561),
    ('Financeiro', 'contas_pagar', 'contas_pagar.criar', 'Criar contas a pagar', 'Permite inserir manualmente contas de fornecedores.', 1562),
    ('Financeiro', 'contas_pagar', 'contas_pagar.editar', 'Editar contas a pagar', 'Permite alterar contas a pagar pendentes.', 1563),
    ('Financeiro', 'contas_pagar', 'contas_pagar.cancelar', 'Cancelar contas a pagar', 'Permite cancelar contas a pagar preservando a auditoria.', 1564),
    ('Financeiro', 'contas_pagar', 'contas_pagar.quitar', 'Quitar parcelas a pagar', 'Permite registrar a quitação individual de parcelas.', 1565),
    ('Financeiro', 'contas_pagar', 'contas_pagar.estornar_pagamento', 'Estornar quitação a pagar', 'Permite estornar quitações preservando o histórico.', 1566),
    ('Financeiro', 'contas_receber', 'contas_receber.visualizar', 'Visualizar contas a receber', 'Permite acessar a carteira de contas a receber.', 1570),
    ('Financeiro', 'contas_receber', 'contas_receber.registrar_pagamento', 'Registrar pagamento de conta', 'Permite registrar pagamentos posteriores de OS.', 1580),
    ('Financeiro', 'contas_receber', 'contas_receber.baixa_lote', 'Baixa em lote', 'Permite registrar baixa em lote de contas do mesmo cliente.', 1585),
    ('Financeiro', 'contas_receber', 'contas_receber.alterar_vencimento', 'Alterar vencimento de conta', 'Permite alterar vencimentos de contas a receber.', 1590),
    ('Financeiro', 'contas_receber', 'contas_receber.configurar_lembrete', 'Configurar lembrete de conta', 'Permite configurar lembretes de cobrança.', 1600),
    ('Financeiro', 'contas_receber', 'contas_receber.registrar_contato', 'Registrar contato de cobrança', 'Permite registrar contatos com clientes.', 1605),
    ('Financeiro', 'contas_receber', 'contas_receber.negociar', 'Registrar negociação de conta', 'Permite registrar negociações de saldo pendente.', 1606),
    ('Financeiro', 'contas_receber', 'contas_receber.estornar_pagamento', 'Estornar pagamento de conta', 'Permite estornar pagamentos preservando histórico.', 1607),

    ('Fiscal', 'nota_fiscal', 'nota_fiscal.visualizar', 'Visualizar notas fiscais', 'Permite acessar notas fiscais.', 1610),
    ('Fiscal', 'nota_fiscal', 'nota_fiscal.emitir', 'Emitir notas fiscais', 'Permite emitir notas fiscais.', 1620),
    ('Fiscal', 'nota_fiscal', 'nota_fiscal.cancelar', 'Cancelar notas fiscais', 'Permite cancelar notas fiscais.', 1630),
    ('Fiscal', 'recibo', 'recibo.visualizar', 'Visualizar recibos', 'Permite acessar recibos.', 1640),
    ('Fiscal', 'recibo', 'recibo.emitir', 'Emitir recibos', 'Permite emitir recibos.', 1650),
    ('Fiscal', 'recibo', 'recibo.reimprimir', 'Reimprimir recibos', 'Permite reimprimir recibos.', 1660),
    ('Fiscal', 'recibo', 'recibo.cancelar', 'Cancelar recibos', 'Permite cancelar recibos.', 1670),
    ('Fiscal', 'boleto', 'boleto.visualizar', 'Visualizar boletos', 'Permite acessar boletos.', 1680),
    ('Fiscal', 'boleto', 'boleto.gerar', 'Gerar boletos', 'Permite gerar boletos.', 1690),
    ('Fiscal', 'boleto', 'boleto.cancelar', 'Cancelar boletos', 'Permite cancelar boletos.', 1700),
    ('Fiscal', 'boleto', 'boleto.registrar_pagamento', 'Registrar pagamento de boleto', 'Permite registrar pagamento interno de boleto sem simular retorno bancário.', 1710),

    ('Relatórios', 'relatorio', 'relatorio.operacional', 'Visualizar relatório operacional', 'Permite acessar relatórios operacionais.', 1810),
    ('Relatórios', 'relatorio', 'relatorio.financeiro', 'Visualizar relatório financeiro', 'Permite acessar relatórios financeiros.', 1820),
    ('Relatórios', 'relatorio', 'relatorio.estoque', 'Visualizar relatório de estoque', 'Permite acessar relatórios de estoque.', 1830),
    ('Relatórios', 'relatorio', 'relatorio.produtividade', 'Visualizar relatório de produtividade', 'Permite acessar relatórios de produtividade.', 1840),
    ('Relatórios', 'relatorio', 'relatorio.funcionarios', 'Visualizar relatório de funcionários', 'Permite acessar relatórios de funcionários.', 1850),
    ('Relatórios', 'relatorio', 'relatorio.comissao.visualizar', 'Visualizar comissões', 'Permite visualizar metas, produção e comissões dos funcionários.', 1855),
    ('Relatórios', 'relatorio', 'relatorio.meta_comissao.configurar', 'Configurar meta de comissão', 'Permite criar uma nova versão da meta e do percentual mensal de comissão.', 1856),
    ('Relatórios', 'relatorio', 'relatorio.exportar', 'Exportar relatórios', 'Permite exportar relatórios.', 1860),
    ('Relatórios', 'relatorio', 'relatorio.imprimir', 'Imprimir relatórios', 'Permite imprimir relatórios.', 1870),

    ('Administração', 'usuario', 'usuario.visualizar', 'Visualizar usuários', 'Permite acessar usuários do sistema.', 1910),
    ('Administração', 'usuario', 'usuario.criar', 'Criar usuários', 'Permite cadastrar usuários do sistema.', 1920),
    ('Administração', 'usuario', 'usuario.editar', 'Editar usuários', 'Permite alterar usuários do sistema.', 1930),
    ('Administração', 'usuario', 'usuario.ativar', 'Ativar usuários', 'Permite ativar usuários do sistema.', 1940),
    ('Administração', 'usuario', 'usuario.bloquear', 'Bloquear usuários', 'Permite bloquear usuários do sistema.', 1950),
    ('Administração', 'usuario', 'usuario.desativar', 'Desativar usuários', 'Permite desativar usuários do sistema.', 1960),
    ('Administração', 'usuario', 'usuario.redefinir_senha', 'Redefinir senha de usuário', 'Permite redefinir senha de usuários.', 1970),
    ('Administração', 'perfil', 'perfil.visualizar', 'Visualizar perfis', 'Permite acessar perfis de acesso.', 2010),
    ('Administração', 'perfil', 'perfil.criar', 'Criar perfis', 'Permite cadastrar perfis de acesso.', 2020),
    ('Administração', 'perfil', 'perfil.editar', 'Editar perfis', 'Permite alterar perfis de acesso.', 2030),
    ('Administração', 'perfil', 'perfil.duplicar', 'Duplicar perfis', 'Permite duplicar perfis de acesso.', 2040),
    ('Administração', 'perfil', 'perfil.desativar', 'Desativar perfis', 'Permite desativar perfis de acesso.', 2050),
    ('Administração', 'perfil', 'perfil.excluir', 'Excluir perfis', 'Permite excluir perfis de acesso.', 2060),
    ('Administração', 'perfil', 'perfil.configurar_permissoes', 'Configurar permissões de perfil', 'Permite configurar permissões vinculadas a perfis.', 2070),
    ('Administração', 'configuracao', 'configuracao.visualizar', 'Visualizar configurações', 'Permite acessar configurações do sistema.', 2110),
    ('Administração', 'configuracao', 'configuracao.editar', 'Editar configurações', 'Permite alterar configurações do sistema.', 2120),
    ('Administração', 'auditoria', 'auditoria.visualizar', 'Visualizar auditoria', 'Permite acessar registros de auditoria.', 2210),
    ('Administração', 'auditoria', 'auditoria.exportar', 'Exportar auditoria', 'Permite exportar registros de auditoria.', 2220)
ON DUPLICATE KEY UPDATE
    grupo = VALUES(grupo),
    modulo = VALUES(modulo),
    nome = VALUES(nome),
    descricao = VALUES(descricao),
    ordem = VALUES(ordem),
    status = 'ativo';
