<?php
declare(strict_types=1);
use Sigesp\Core\View;

$title = 'Atletas';
$pageId = 'atletas';
$items = (array) ($result['items'] ?? $atletas ?? []);
$total = (int) ($result['total'] ?? count($items));
$tone = static function (string $value): string {
    $value = mb_strtolower($value);
    if (str_contains($value,'ativo') && !str_contains($value,'inativo') || str_contains($value,'regular')) return 'success';
    if (str_contains($value,'pend') || str_contains($value,'incompleto')) return 'warning';
    if (str_contains($value,'venc') || str_contains($value,'inativo')) return 'danger';
    return 'neutral';
};
?>
<?php View::component('page-header',['eyebrow'=>'Gestão de atletas · Demonstração','heading'=>'Atletas','description'=>number_format($total,0,',','.') . ' atletas na amostra demonstrativa.','actionLabel'=>'Novo atleta','actionHref'=>'/atletas/novo','secondaryLabel'=>'Exportar','secondaryMessage'=>'A exportação será habilitada na integração com o back-end.']); ?>
<section class="stats-grid"><?php foreach ([['◉','Atletas cadastrados','1.248','Base municipal fictícia'],['✓','Atletas ativos','1.102','88,3% da base'],['+','Novos no mês','84','Crescimento de 7,2%'],['!','Cadastros incompletos','32','Precisam de revisão']] as [$icon,$label,$value,$detail]) View::component('stats-card',compact('icon','label','value','detail')); ?></section>
<?php ob_start(); ?><form class="filter-form" data-demo-filter data-filter-target="#athletes-table"><label class="field">Buscar<input type="search" data-filter-search placeholder="Nome, CPF ou código"></label><label class="field">Modalidade<select data-filter-select><option value="">Todas</option><option>Voleibol</option><option>Futsal</option><option>Atletismo</option><option>Natação</option></select></label><label class="field">Categoria<select data-filter-select><option value="">Todas</option><option>Sub-17</option><option>Sub-20</option><option>Adulto</option></select></label><label class="field">Situação<select data-filter-select><option value="">Todas</option><option>Ativo</option><option>Inativo</option><option>Cadastro incompleto</option></select></label><label class="field">Documentação<select data-filter-select><option value="">Todas</option><option>Regular</option><option>Pendente</option><option>Vencida</option></select></label><div><button class="button" type="submit">Aplicar</button><button class="button button--secondary" type="reset">Limpar</button></div></form><?php $filterContent=ob_get_clean(); View::component('filter-bar',['filters'=>$filterContent]); ?>
<section class="surface" id="athletes-table"><div class="demo-toolbar"><p class="demo-toolbar__summary"><strong data-record-count><?= count($items) ?></strong> atletas exibidos nesta página.</p><div class="demo-toolbar__actions"><button class="button button--secondary" type="button" data-demo-action="print">Imprimir</button><button class="button button--secondary" type="button" data-demo-action="export">Excel/PDF</button></div></div>
<div class="data-table demo-table"><table><thead><tr><th scope="col">Atleta</th><th scope="col">Código / CPF</th><th scope="col">Idade</th><th scope="col">Modalidade</th><th scope="col">Equipe</th><th scope="col">Documentos</th><th scope="col">Frequência</th><th scope="col">Situação</th><th scope="col">Ações</th></tr></thead><tbody><?php foreach($items as $item): ?><?php $name=(string)($item['nome']??'Atleta demonstrativo'); $id=(int)($item['id']??1); ?><tr data-demo-record data-search-text="<?= View::e(mb_strtolower(implode(' ',array_map('strval',$item)))) ?>"><td><div class="demo-record-title"><?php View::component('avatar',['name'=>$name]); ?><div><strong><?= View::e($name) ?></strong><small><?= View::e((string)($item['email']??'atleta@demonstracao.local')) ?></small></div></div></td><td><strong><?= View::e((string)($item['codigo']??'ATL-2026-0001')) ?></strong><small><?= View::e((string)($item['cpf']??'***.***.***-00')) ?></small></td><td><?= View::e((string)($item['idade']??'18')) ?> anos</td><td><?= View::e((string)($item['modalidade']??'Voleibol')) ?><small><?= View::e((string)($item['categoria']??'Sub-20')) ?></small></td><td><?= View::e((string)($item['equipe']??'Equipe Municipal')) ?></td><td><?php $docs=(string)($item['documentos_status']??$item['documentos']??'Regular'); View::component('badge',['label'=>$docs,'tone'=>$tone($docs)]); ?></td><td><strong><?= View::e((string)($item['frequencia']??'90')) ?>%</strong><span class="progress"><i style="width:<?= max(0,min(100,(int)($item['frequencia']??90))) ?>%"></i></span></td><td><?php $status=(string)($item['status']??'Ativo'); View::component('badge',['label'=>$status,'tone'=>$tone($status)]); ?></td><td><div class="demo-actions"><a class="button button--secondary" href="<?= View::e(View::url('/atletas/'.$id)) ?>">Perfil</a><div class="dropdown" data-dropdown><button class="button button--secondary demo-actions__menu" type="button" data-dropdown-toggle aria-expanded="false" aria-label="Ações de <?= View::e($name) ?>">⋯</button><div class="dropdown__menu dropdown__menu--right" data-dropdown-menu hidden><a href="<?= View::e(View::url('/atletas/'.$id.'/editar')) ?>">Editar</a><a href="<?= View::e(View::url('/atletas/'.$id.'/documentos')) ?>">Documentos</a><a href="<?= View::e(View::url('/atletas/'.$id.'/carteira')) ?>">Carteira digital</a><button type="button" data-demo-delete data-record-name="<?= View::e($name) ?>">Inativar</button></div></div></div></td></tr><?php endforeach; ?></tbody></table></div>
<section class="record-cards" aria-label="Atletas em cartões"><?php foreach($items as $item): ?><?php $id=(int)($item['id']??1); ?><article class="record-card" data-demo-record data-search-text="<?= View::e(mb_strtolower(implode(' ',array_map('strval',$item)))) ?>"><div class="record-card__head"><?php View::component('avatar',['name'=>(string)($item['nome']??'Atleta')]); ?><div><strong><?= View::e((string)($item['nome']??'Atleta')) ?></strong><small><?= View::e((string)($item['codigo']??'ATL-2026')) ?> · <?= View::e((string)($item['modalidade']??'Voleibol')) ?></small></div><?php View::component('badge',['label'=>(string)($item['status']??'Ativo'),'tone'=>$tone((string)($item['status']??'Ativo'))]); ?></div><div class="record-card__meta"><span><?= View::e((string)($item['documentos_status']??'Regular')) ?></span><span><?= View::e((string)($item['frequencia']??90)) ?>% frequência</span><a class="button button--secondary" href="<?= View::e(View::url('/atletas/'.$id)) ?>">Ver perfil</a></div></article><?php endforeach; ?></section>
</section>
