<?php
declare(strict_types=1);
use Sigesp\Core\View;

$atleta = is_array($atleta ?? null) ? $atleta : [];
$id = (int) ($atleta['id'] ?? 1);
$name = (string) ($atleta['nome'] ?? 'Ana Beatriz Souza');
$title = $name;
$pageId = 'atleta-perfil';
$tabs = ['visao'=>'Visão geral','pessoal'=>'Dados pessoais','endereco'=>'Endereço','responsavel'=>'Responsável','esportivo'=>'Perfil esportivo','documentos'=>'Documentos','equipe'=>'Equipe','treinos'=>'Treinos','frequencia'=>'Frequência','avaliacoes'=>'Avaliações','competicoes'=>'Competições','resultados'=>'Resultados','beneficios'=>'Benefícios','ocorrencias'=>'Ocorrências','historico'=>'Histórico'];
?>
<section class="surface"><div class="profile-hero"><span class="avatar avatar--large"><?= View::e(mb_strtoupper(mb_substr($name,0,2))) ?></span><div class="profile-hero__copy"><p class="eyebrow"><?= View::e((string)($atleta['codigo']??'ATL-2026-0001')) ?></p><h1><?= View::e($name) ?></h1><p><?= View::e((string)($atleta['idade']??18)) ?> anos · <?= View::e((string)($atleta['modalidade']??'Voleibol')) ?> · <?= View::e((string)($atleta['equipe']??'Seleção Municipal Feminina')) ?></p></div><?php View::component('badge',['label'=>(string)($atleta['status']??'Ativo'),'tone'=>'success']); ?><div class="profile-hero__actions"><a class="button button--secondary" href="<?= View::e(View::url('/atletas/'.$id.'/editar')) ?>">Editar</a><a class="button" href="<?= View::e(View::url('/atletas/'.$id.'/documentos')) ?>">Documentos</a><a class="button button--secondary" href="<?= View::e(View::url('/atletas/'.$id.'/carteira')) ?>">Carteira</a></div></div></section>
<section class="stats-grid"><?php foreach ([['✓','Frequência',(string)($atleta['frequencia']??92).'%','Últimos 30 dias'],['▣','Documentos',(string)($atleta['documentos_status']??'Regular'),'Cadastro demonstrativo'],['★','Competições','6','Duas no ano atual'],['⌁','Avaliações','8,7','Evolução positiva']] as [$icon,$label,$value,$detail]) View::component('stats-card',compact('icon','label','value','detail')); ?></section>
<section class="surface" data-tabs-root>
    <div class="tabs" role="tablist" aria-label="Informações do atleta"><?php foreach($tabs as $key=>$label): ?><button type="button" id="athlete-tab-<?= View::e($key) ?>" data-tab-target="athlete-panel-<?= View::e($key) ?>" role="tab" aria-controls="athlete-panel-<?= View::e($key) ?>" aria-selected="<?= $key==='visao'?'true':'false' ?>"><?= View::e($label) ?></button><?php endforeach; ?></div>
    <?php foreach($tabs as $key=>$label): ?><section id="athlete-panel-<?= View::e($key) ?>" data-tab-panel role="tabpanel" aria-labelledby="athlete-tab-<?= View::e($key) ?>" <?= $key==='visao'?'':'hidden' ?>>
        <?php if($key==='visao'): ?><div class="dashboard-grid"><article><h2>Resumo do perfil</h2><dl class="details-list"><dt>CPF</dt><dd><?= View::e((string)($atleta['cpf']??'***.***.***-21')) ?></dd><dt>Nascimento</dt><dd><?= View::e((string)($atleta['nascimento_formatada']??'14/05/2008')) ?></dd><dt>Telefone</dt><dd><?= View::e((string)($atleta['telefone']??'(97) 99999-1021')) ?></dd><dt>Bairro</dt><dd><?= View::e((string)($atleta['bairro']??'Centro')) ?></dd></dl></article><aside><h2>Próximas atividades</h2><?php View::component('activity-timeline',['items'=>[['title'=>'Treino técnico','detail'=>'Hoje, 18h · Ginásio Municipal'],['title'=>'Avaliação física','detail'=>'08/08, 15h · Centro Esportivo'],['title'=>'Copa Municipal','detail'=>'15/08, 9h · Arena Norte']]]); ?></aside></div>
        <?php elseif($key==='pessoal'): ?><h2>Dados pessoais</h2><dl class="details-list"><dt>Nome completo</dt><dd><?= View::e($name) ?></dd><dt>E-mail</dt><dd><?= View::e((string)($atleta['email']??'ana.beatriz@demonstracao.local')) ?></dd><dt>Sexo</dt><dd><?= View::e((string)($atleta['sexo']??'Feminino')) ?></dd><dt>Cadastro</dt><dd>12/02/2026</dd></dl>
        <?php elseif($key==='endereco'): ?><h2>Endereço</h2><dl class="details-list"><dt>Logradouro</dt><dd>Rua das Quadras, 100</dd><dt>Bairro</dt><dd><?= View::e((string)($atleta['bairro']??'Centro')) ?></dd><dt>Município</dt><dd>Município Demonstrativo</dd><dt>CEP</dt><dd>69000-000</dd></dl>
        <?php elseif($key==='responsavel'): ?><h2>Responsável legal</h2><dl class="details-list"><dt>Nome</dt><dd>Juliana Martins</dd><dt>Parentesco</dt><dd>Mãe</dd><dt>Contato</dt><dd>(97) 99999-0010</dd><dt>Autorização</dt><dd><?php View::component('badge',['label'=>'Assinada','tone'=>'success']); ?></dd></dl>
        <?php elseif($key==='esportivo'): ?><h2>Perfil esportivo</h2><dl class="details-list"><dt>Modalidade</dt><dd><?= View::e((string)($atleta['modalidade']??'Voleibol')) ?></dd><dt>Categoria</dt><dd><?= View::e((string)($atleta['categoria']??'Sub-20')) ?></dd><dt>Equipe</dt><dd><?= View::e((string)($atleta['equipe']??'Seleção Municipal Feminina')) ?></dd><dt>Posição</dt><dd>Ponteira</dd></dl>
        <?php elseif($key==='documentos'): ?><div class="surface__header"><div><h2>Documentos</h2><p>4 regulares e 1 próximo do vencimento.</p></div><a href="<?= View::e(View::url('/atletas/'.$id.'/documentos')) ?>">Abrir central</a></div><div class="module-highlights"><article class="module-highlight"><strong>Identidade</strong><span>Aprovado · validade permanente</span></article><article class="module-highlight"><strong>Atestado médico</strong><span>Vence em 28 dias</span></article><article class="module-highlight"><strong>Autorização</strong><span>Assinada pelo responsável</span></article></div>
        <?php elseif($key==='frequencia'): ?><h2>Frequência mensal</h2><div class="demo-chart"><?php foreach([['Abril',88],['Maio',91],['Junho',94],['Julho',92]] as [$month,$percent]): ?><div class="demo-chart__row"><span><?= $month ?></span><span class="demo-chart__track"><i class="demo-chart__bar" style="width:<?= $percent ?>%"></i></span><strong><?= $percent ?>%</strong></div><?php endforeach; ?></div>
        <?php else: ?><div class="surface__header"><div><h2><?= View::e($label) ?></h2><p>Histórico fictício organizado para apresentação.</p></div></div><?php View::component('activity-timeline',['items'=>[['title'=>$label.' atualizado','detail'=>'Hoje · Administrador Demonstrativo'],['title'=>'Registro conferido','detail'=>'02/08/2026 · Gestão Esportiva'],['title'=>'Informação incluída','detail'=>'18/07/2026 · Modo demonstração']]]); ?>
        <?php endif; ?>
    </section><?php endforeach; ?>
</section>
