-- FluxEmpresa: somente Serviços e Ordens de Serviço.
-- Não possui campos GENERATED; compatível com MySQL/MariaDB comuns.
CREATE DATABASE IF NOT EXISTS fluxempresa CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fluxempresa;

CREATE TABLE IF NOT EXISTS servicos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(20) NULL,
    nome VARCHAR(150) NOT NULL,
    categoria VARCHAR(100) NULL,
    equipamentos_compativeis VARCHAR(255) NULL,
    duracao_minutos INT UNSIGNED NOT NULL DEFAULT 0,
    valor DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    descricao TEXT NULL,
    status ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
    excluido_em DATETIME NULL,
    excluido_por INT UNSIGNED NULL,
    motivo_exclusao VARCHAR(255) NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_servicos_codigo (codigo),
    KEY idx_servicos_nome (nome),
    KEY idx_servicos_categoria (categoria),
    KEY idx_servicos_status (status),
    KEY idx_servicos_exclusao (excluido_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ordens_servico (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(20) NULL,
    cliente_id INT UNSIGNED NOT NULL,
    orcamento_id INT UNSIGNED NULL,
    orcamento_liberado TINYINT(1) NOT NULL DEFAULT 0,
    ordem_substituta_id INT UNSIGNED NULL,
    funcionario_principal_id INT UNSIGNED NULL,
    funcionario_apoio_id INT UNSIGNED NULL,
    agendado_inicio DATETIME NULL,
    agendado_fim DATETIME NULL,
    status ENUM('rascunho','aberta','aguardando_agendamento','agendada','em_deslocamento','em_execucao','aguardando_peca','finalizada','cancelada') NOT NULL DEFAULT 'aberta',
    prioridade ENUM('baixa','media','alta','urgente') NOT NULL DEFAULT 'media',
    equipamento_tipo VARCHAR(100) NULL,
    equipamento_marca VARCHAR(100) NULL,
    equipamento_modelo VARCHAR(100) NULL,
    equipamento_capacidade VARCHAR(100) NULL,
    equipamento_numero_serie VARCHAR(100) NULL,
    equipamento_ambiente VARCHAR(100) NULL,
    equipamento_local VARCHAR(150) NULL,
    problema_relatado TEXT NULL,
    problema_identificado TEXT NULL,
    diagnostico TEXT NULL,
    solucao TEXT NULL,
    recomendacao TEXT NULL,
    observacoes_internas TEXT NULL,
    observacoes TEXT NULL,
    subtotal_servicos DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    subtotal_produtos DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    subtotal_outros DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    desconto DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    acrescimo DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    valor_aprovado_orcamento DECIMAL(12,2) NULL,
    finalizada_em DATETIME NULL,
    cancelada_em DATETIME NULL,
    excluida_em DATETIME NULL,
    excluida_por INT UNSIGNED NULL,
    motivo_exclusao VARCHAR(255) NULL,
    orcamento_operacional_chave INT UNSIGNED NULL,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ordens_servico_numero (numero),
    UNIQUE KEY uq_os_orcamento_operacional_unico (orcamento_operacional_chave),
    KEY idx_os_cliente (cliente_id),
    KEY idx_os_orcamento (orcamento_id),
    KEY idx_os_status (status),
    KEY idx_os_agendado_inicio (agendado_inicio),
    KEY idx_os_agendado_fim (agendado_fim),
    KEY idx_os_orcamento_operacional (orcamento_id, status, orcamento_liberado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ordem_servico_itens (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ordem_servico_id INT UNSIGNED NOT NULL,
    tipo ENUM('servico','produto','outro') NOT NULL,
    origem ENUM('orcamento','manual','finalizacao') NOT NULL DEFAULT 'manual',
    referencia_id INT UNSIGNED NULL,
    orcamento_item_id INT UNSIGNED NULL,
    descricao VARCHAR(255) NOT NULL,
    unidade VARCHAR(20) NOT NULL DEFAULT 'un',
    quantidade DECIMAL(12,3) NOT NULL DEFAULT 1.000,
    valor_unitario DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    desconto DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ordem INT UNSIGNED NOT NULL DEFAULT 0,
    criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_os_itens_ordem_servico (ordem_servico_id),
    KEY idx_os_itens_origem (origem),
    CONSTRAINT fk_os_itens_ordem_servico FOREIGN KEY (ordem_servico_id)
        REFERENCES ordens_servico(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
