<?php
use Sigesp\Core\{Auth, Csrf, Flash, View};
$user = Auth::user();
$flash = Flash::pull();
$currentPath = parse_url($_SERVER['REQUEST_URI'] ?? '/dashboard', PHP_URL_PATH) ?: '/dashboard';
$menu = [
    ['Visão geral', '/dashboard', '⌂'],
    ['Gestão de atletas', null, null], ['Atletas', '/atletas', '◉'], ['Novo atleta', '/atletas/novo', '+'], ['Responsáveis', '/responsaveis', '♙'], ['Documentos', '/documentos', '▣'], ['Carteiras digitais', '#', '▤'],
    ['Gestão esportiva', null, null], ['Modalidades', '/modalidades', '◌'], ['Categorias', '/categorias', '◫'], ['Equipes', '/equipes', '♜'], ['Treinos', '/treinos', '◷'], ['Frequências', '/frequencias', '✓'], ['Avaliações', '/avaliacoes', '⌁'],
    ['Eventos e competições', null, null], ['Eventos', '/eventos', '★'], ['Competições', '/competicoes', '⌘'], ['Inscrições', '/inscricoes', '⊕'], ['Resultados', '/resultados', '♕'],
    ['Recursos', null, null], ['Benefícios', '/beneficios', '♥'], ['Espaços esportivos', '/espacos-esportivos', '⌂'], ['Reservas', '/reservas', '◴'], ['Materiais esportivos', '/materiais', '▤'],
    ['Relatórios', '/relatorios', '▥'], ['Administração', null, null], ['Usuários', '/usuarios', '♙'], ['Perfis e permissões', '/permissoes', '⚿'], ['Auditoria', '/auditoria', '◷'], ['Configurações', '/configuracoes', '⚙'],
];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10233F"><title><?= View::e($title ?? 'SIGESP') ?> · SIGESP</title><link rel="stylesheet" href="/assets/css/app.css"></head>
<body data-page="<?= View::e($pageId ?? '') ?>"><aside class="sidebar" id="sidebar" aria-label="Menu principal"><div class="sidebar__head"><a class="brand" href="/dashboard"><span class="brand-mark">S</span><span><strong>SIGESP</strong><small>Gestão Esportiva</small></span></a><button class="sidebar__compact icon-button" type="button" data-sidebar-compact aria-label="Recolher menu">‹</button></div><nav class="sidebar__nav"><?php foreach ($menu as [$label, $href, $icon]): ?><?php if ($href === null): ?><p><?= View::e($label) ?></p><?php else: ?><a href="<?= View::e($href) ?>" class="<?= $href !== '#' && ($currentPath === $href || ($href !== '/dashboard' && str_starts_with($currentPath, $href . '/'))) ? 'is-active' : '' ?>"<?= $href === '#' ? ' data-toast="Carteiras digitais estão preparadas para a próxima etapa operacional."' : '' ?>><span aria-hidden="true"><?= View::e($icon) ?></span><b><?= View::e($label) ?></b></a><?php endif; ?><?php endforeach; ?></nav><footer class="sidebar__user"><?php View::component('avatar', ['name' => $user['nome'] ?? 'Usuário']); ?><div><strong><?= View::e($user['nome'] ?? 'Usuário') ?></strong><small>Ambiente administrativo</small></div><form method="post" action="/logout"><input type="hidden" name="_token" value="<?= Csrf::token() ?>"><button class="icon-button" type="submit" aria-label="Sair">↪</button></form></footer></aside><div class="app-backdrop" data-sidebar-close></div>
<main class="app-main"><header class="topbar"><div class="topbar__start"><button class="icon-button topbar__menu" type="button" data-sidebar-toggle aria-label="Abrir menu">☰</button><?php View::component('breadcrumb', ['items' => [$title ?? 'Painel']]); ?></div><div class="topbar__actions"><button class="icon-button topbar__search" type="button" data-toast="A pesquisa global será conectada aos módulos disponíveis." aria-label="Pesquisar">⌕</button><label class="global-search"><span aria-hidden="true">⌕</span><input type="search" placeholder="Pesquisar no SIGESP" aria-label="Pesquisar no SIGESP"></label><button class="icon-button" type="button" data-toast="Nenhuma nova notificação." aria-label="Notificações">♧</button><button class="icon-button fullscreen-button" type="button" data-fullscreen-toggle aria-label="Alternar tela cheia">⛶</button><div class="user-menu" data-dropdown><button class="user-menu__trigger" type="button" data-dropdown-toggle aria-expanded="false"><?php View::component('avatar', ['name' => $user['nome'] ?? 'Usuário']); ?><span><?= View::e($user['nome'] ?? 'Usuário') ?></span></button><div class="dropdown__menu dropdown__menu--right" data-dropdown-menu hidden><a href="/configuracoes">Configurações</a><form method="post" action="/logout"><input type="hidden" name="_token" value="<?= Csrf::token() ?>"><button type="submit">Sair</button></form></div></div></div></header><?php if ($flash): ?><div class="alert alert--<?= View::e($flash['type']) ?>" role="status"><?= View::e($flash['message']) ?></div><?php endif; ?><?= $content ?></main><?php View::component('toast'); ?><script src="/assets/js/app.js" type="module"></script></body></html>
