-- Migration: Enhance OS Features
ALTER TABLE os 
ADD COLUMN IF NOT EXISTS fotos JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS assinatura_digital TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sla_prazo_horas INT DEFAULT 48,
ADD COLUMN IF NOT EXISTS data_vencimento_sla DATETIME DEFAULT NULL;
