<?php

declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/repository.php';
require_once dirname(__DIR__) . '/lib/list-ui.php';
$pageDefinition=['title'=>'Capacitações','description'=>'Cursos, oficinas e participação dos candidatos nas ações de qualificação.','demo'=>false,'show_states'=>false,'actions'=>[],'modal'=>['title'=>'Capacitação']];
$dbReady=pe_db_ready()&&pe_program_schema_ready();$message=null;$rows=[];$candidates=[];
if($dbReady){$pdo=pe_db();$candidates=pe_program_candidates($pdo);if($_SERVER['REQUEST_METHOD']==='POST'){try{pe_verify_csrf();$action=(string)($_POST['pe_action']??'');$id=(int)($_POST['id']??0);if($action==='save_training'){if($id>0){pe_update_training($pdo,$id,$_POST);$message=['type'=>'success','text'=>'Capacitação atualizada com sucesso.'];}else{pe_save_training($pdo,$_POST);$message=['type'=>'success','text'=>'Capacitação cadastrada com sucesso.'];}}elseif($action==='delete_training'){pe_delete_training($pdo,$id);$message=['type'=>'success','text'=>'Capacitação excluída com sucesso.'];}elseif($action==='enroll_training'){pe_enroll_training($pdo,$_POST);$message=['type'=>'success','text'=>'Participante inscrito na capacitação.'];}}catch(Throwable $e){$message=['type'=>'danger','text'=>$e->getMessage()];}}$rows=pe_trainings($pdo);}
$metrics=[
 ['label'=>'Capacitações','value'=>count($rows),'hint'=>'ações cadastradas','tone'=>'neutral'],
 ['label'=>'Planejadas','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Planejada'),'hint'=>'preparação','tone'=>'info','filter_key'=>'status','filter_value'=>'Planejada'],
 ['label'=>'Inscrições abertas','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Inscrições abertas'),'hint'=>'recebendo participantes','tone'=>'success','filter_key'=>'status','filter_value'=>'Inscrições abertas'],
 ['label'=>'Em andamento','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Em andamento'),'hint'=>'turmas ativas','tone'=>'info','filter_key'=>'status','filter_value'=>'Em andamento'],
 ['label'=>'Concluídas','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Concluída'),'hint'=>array_sum(array_map(static fn($r)=>(int)($r['concluintes']??0),$rows)).' concluinte(s)','tone'=>'success','filter_key'=>'status','filter_value'=>'Concluída'],
 ['label'=>'Canceladas','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Cancelada'),'hint'=>'histórico/atenção','tone'=>'danger','filter_key'=>'status','filter_value'=>'Cancelada'],
];
$institutionOptions=pe_filter_options($rows,'instituicao','Todas as instituições');
$certificateOptions=pe_filter_options($rows,'certificado','Todos os certificados');
ob_start();?>
<section class="content-card pe-form-card pe-page pe-list-page">
<?php if(!$dbReady):?><div class="alert alert-warning">Execute <code>database/primeiroEmprego/0003-primeiroEmprego-programa.sql</code>.</div><?php endif;?><?php if($message):?><div class="alert alert-<?=pe_h($message['type'])?>"><?=pe_h($message['text'])?></div><?php endif;?>
<?php pe_list_header('Qualificação','Capacitações cadastradas','A listagem é a tela principal. Cadastro, edição, exclusão e inscrição de participantes abrem em modal.','Nova capacitação','#peTrainingForm','mortarboard'); ?>
<?php pe_list_metrics($metrics,'#peTrainingFilters'); ?>
<div class="pe-page-actions pe-no-print mb-3"><button class="btn btn-light" type="button" data-pe-open="#peEnrollmentForm" data-pe-mode="create"><i class="bi bi-person-plus"></i> Inscrever participante</button></div>
    <?php pe_list_filter_panel('peTrainingTable','Buscar curso, instituição, turma ou observação...',[
 ['key'=>'status','label'=>'Status','options'=>[''=>'Todos os status','Planejada'=>'Planejada','Inscrições abertas'=>'Inscrições abertas','Em andamento'=>'Em andamento','Concluída'=>'Concluída','Cancelada'=>'Cancelada']],
 ['key'=>'instituicao','label'=>'Instituição','options'=>$institutionOptions],
 ['key'=>'certificado','label'=>'Certificado','options'=>$certificateOptions],
],count($rows),'capacitação(ões)'); ?>
<div class="pe-table-wrap"><div class="table-responsive"><table id="peTrainingTable" class="table align-middle pe-data-table pe-list-table" data-pe-list-table><thead><tr><th>Curso</th><th>Instituição</th><th>Turma</th><th>Carga</th><th>Período</th><th>Inscritos</th><th>Concluintes</th><th>Certificado</th><th>Status</th></tr></thead><tbody>
<?php if(!$rows):?><tr class="pe-empty-row"><td colspan="9" class="text-center text-muted py-5">Nenhuma capacitação cadastrada.</td></tr><?php endif;?>
<?php foreach($rows as $r):$record=$r;$record['__title']=$r['curso'];$record['__subtitle']=($r['turma']?:'Sem turma').' · '.$r['status'];$record['periodo_formatado']=($r['data_inicio']?date('d/m/Y',strtotime((string)$r['data_inicio'])):'—').($r['data_fim']?' a '.date('d/m/Y',strtotime((string)$r['data_fim'])):'');$record['carga_formatada']=$r['carga_horaria']!==null?(int)$r['carga_horaria'].'h':'—';?>
<tr class="pe-list-row" tabindex="0" role="button" data-pe-list-row data-pe-actions-target="#peTrainingActions" data-pe-record="<?=pe_record_attr($record)?>" data-pe-filter-status="<?=pe_h((string)$r['status'])?>" data-pe-filter-instituicao="<?=pe_h((string)($r['instituicao']??''))?>" data-pe-filter-certificado="<?=pe_h((string)($r['certificado']??''))?>"><td data-label="Curso"><strong><?=pe_h($r['curso'])?></strong></td><td data-label="Instituição"><?=pe_h($r['instituicao']?:'—')?></td><td data-label="Turma"><?=pe_h($r['turma']?:'—')?></td><td data-label="Carga"><?=pe_h($record['carga_formatada'])?></td><td data-label="Período"><?=pe_h($record['periodo_formatado'])?></td><td data-label="Inscritos"><?=(int)$r['inscritos']?></td><td data-label="Concluintes"><?=(int)$r['concluintes']?></td><td data-label="Certificado"><span class="<?=pe_h(pe_status_class($r['certificado']))?>"><?=pe_h($r['certificado'])?></span></td><td data-label="Status"><?=pe_status_label($r['status'])?></td></tr>
<?php endforeach;?></tbody></table></div><div class="pe-filter-empty" data-pe-filter-empty hidden>Nenhuma capacitação corresponde aos filtros selecionados.</div></div>
<?php pe_crud_actions_dialog('peTrainingActions','Capacitação','#peTrainingView','#peTrainingForm','#peTrainingDelete'); ?>
<dialog class="pe-modal pe-modal--form" id="peTrainingForm" data-pe-create-title="Nova capacitação" data-pe-edit-title="Editar capacitação"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Qualificação</div><h2 data-pe-form-title>Nova capacitação</h2><p>Cadastre os dados da ação de qualificação.</p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><form method="post" class="pe-action-form" data-pe-record-form><?=pe_csrf_field()?><input type="hidden" name="pe_action" value="save_training"><input type="hidden" name="id" data-pe-field="id"><div class="pe-action-form-grid pe-action-form-grid--3"><div class="pe-field-span-2"><label class="form-label required">Curso/oficina</label><input class="form-control" name="curso" data-pe-field="curso" required maxlength="180"></div><div><label class="form-label">Instituição</label><input class="form-control" name="instituicao" data-pe-field="instituicao" maxlength="180"></div><div><label class="form-label">Turma</label><input class="form-control" name="turma" data-pe-field="turma" maxlength="80"></div><div><label class="form-label">Carga (h)</label><input class="form-control" type="number" min="0" name="carga_horaria" data-pe-field="carga_horaria"></div><div><label class="form-label">Vagas</label><input class="form-control" type="number" min="0" name="vagas" data-pe-field="vagas"></div><div><label class="form-label">Início</label><input class="form-control" type="date" name="data_inicio" data-pe-field="data_inicio"></div><div><label class="form-label">Fim</label><input class="form-control" type="date" name="data_fim" data-pe-field="data_fim"></div><div><label class="form-label">Certificado</label><select class="form-select" name="certificado" data-pe-field="certificado"><?php foreach(['Previsto','Disponível','Não se aplica'] as $v):?><option><?=pe_h($v)?></option><?php endforeach;?></select></div><div><label class="form-label">Status</label><select class="form-select" name="status" data-pe-field="status"><?php foreach(['Planejada','Inscrições abertas','Em andamento','Concluída','Cancelada'] as $v):?><option><?=pe_h($v)?></option><?php endforeach;?></select></div><div class="pe-field-span-3"><label class="form-label">Observação</label><textarea class="form-control" name="observacao" data-pe-field="observacao" rows="3"></textarea></div></div><footer class="pe-action-modal-footer"><button type="button" class="btn btn-light" data-pe-dialog-close>Cancelar</button><button class="btn btn-primary" type="submit"><i class="bi bi-floppy"></i> Salvar capacitação</button></footer></form></div></div></dialog>
<dialog class="pe-modal pe-modal--form" id="peEnrollmentForm" data-pe-create-title="Inscrever participante"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Participante</div><h2>Inscrever em capacitação</h2><p>Vincule um candidato a uma ação de qualificação.</p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><form method="post" class="pe-action-form"><?=pe_csrf_field()?><input type="hidden" name="pe_action" value="enroll_training"><div class="pe-action-form-grid pe-action-form-grid--2"><div><label class="form-label required">Capacitação</label><select class="form-select" name="capacitacao_id" required><option value="">Selecione...</option><?php foreach($rows as $r):?><option value="<?=(int)$r['id']?>"><?=pe_h($r['curso'])?><?= $r['turma']?' — '.pe_h($r['turma']):''?></option><?php endforeach;?></select></div><div><label class="form-label required">Candidato</label><select class="form-select" name="candidato_id" required><option value="">Selecione...</option><?php foreach($candidates as $c):?><option value="<?=(int)$c['id']?>"><?=pe_h($c['nome'])?></option><?php endforeach;?></select></div></div><footer class="pe-action-modal-footer"><button type="button" class="btn btn-light" data-pe-dialog-close>Cancelar</button><button class="btn btn-primary" type="submit"><i class="bi bi-person-plus"></i> Inscrever</button></footer></form></div></div></dialog>
<dialog class="pe-modal pe-modal--view" id="peTrainingView"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Capacitação</div><h2 data-pe-current-title>Detalhes</h2><p data-pe-current-subtitle></p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><dl class="pe-modal-details pe-modal-details--3"><div><dt>Instituição</dt><dd data-pe-text="instituicao">—</dd></div><div><dt>Turma</dt><dd data-pe-text="turma">—</dd></div><div><dt>Carga</dt><dd data-pe-text="carga_formatada">—</dd></div><div><dt>Período</dt><dd data-pe-text="periodo_formatado">—</dd></div><div><dt>Vagas</dt><dd data-pe-text="vagas">—</dd></div><div><dt>Status</dt><dd data-pe-text="status">—</dd></div><div><dt>Inscritos</dt><dd data-pe-text="inscritos">0</dd></div><div><dt>Concluintes</dt><dd data-pe-text="concluintes">0</dd></div><div><dt>Certificado</dt><dd data-pe-text="certificado">—</dd></div></dl><div class="pe-view-note"><strong>Observação</strong><p data-pe-text="observacao">—</p></div></div></div></dialog>
<?php pe_delete_dialog('peTrainingDelete','capacitação','delete_training'); ?>
</section>
<?php $pageCustomContent=(string)ob_get_clean();
