<?php

declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/repository.php';
require_once dirname(__DIR__) . '/lib/list-ui.php';
$pageDefinition=['title'=>'Documentação','description'=>'Conferência e armazenamento seguro dos documentos dos candidatos e contemplados.','demo'=>false,'show_states'=>false,'actions'=>[],'modal'=>['title'=>'Documentação']];
$dbReady=pe_db_ready()&&pe_program_schema_ready();$message=null;$rows=[];$candidates=[];
if($dbReady){$pdo=pe_db();$candidates=pe_program_candidates($pdo);if($_SERVER['REQUEST_METHOD']==='POST'){try{pe_verify_csrf();$action=(string)($_POST['pe_action']??'');$id=(int)($_POST['id']??0);if($action==='save_document'){if($id>0){pe_update_document($pdo,$id,$_POST,$_FILES,pe_current_user_label());$message=['type'=>'success','text'=>'Documento atualizado com sucesso.'];}else{pe_save_document($pdo,$_POST,$_FILES,pe_current_user_label());$message=['type'=>'success','text'=>'Documento registrado com sucesso.'];}}elseif($action==='delete_document'){pe_delete_document($pdo,$id);$message=['type'=>'success','text'=>'Documento excluído com sucesso.'];}}catch(Throwable $e){$message=['type'=>'danger','text'=>$e->getMessage()];}}$rows=pe_documents($pdo);}
$metrics=[
 ['label'=>'Documentos','value'=>count($rows),'hint'=>'itens registrados','tone'=>'neutral'],
 ['label'=>'Regulares','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Regular'),'hint'=>'sem pendência','tone'=>'success','filter_key'=>'status','filter_value'=>'Regular'],
 ['label'=>'Pendentes','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Pendente'),'hint'=>'aguardando envio/conferência','tone'=>'warning','filter_key'=>'status','filter_value'=>'Pendente'],
 ['label'=>'Revisar','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Revisar'),'hint'=>'exigem conferência','tone'=>'warning','filter_key'=>'status','filter_value'=>'Revisar'],
 ['label'=>'Vencidos','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Vencido'),'hint'=>'ação necessária','tone'=>'danger','filter_key'=>'status','filter_value'=>'Vencido'],
 ['label'=>'Sem arquivo','value'=>pe_count_rows($rows,fn($r)=>empty($r['arquivo_path'])),'hint'=>'registro sem anexo','tone'=>'warning','filter_key'=>'arquivo','filter_value'=>'Sem arquivo'],
];
$typeOptions=pe_filter_options($rows,'tipo','Todos os documentos');
ob_start();?>
<section class="content-card pe-form-card pe-page pe-list-page">
<?php if(!$dbReady):?><div class="alert alert-warning">Execute <code>database/primeiroEmprego/0003-primeiroEmprego-programa.sql</code>.</div><?php endif;?><?php if($message):?><div class="alert alert-<?=pe_h($message['type'])?>"><?=pe_h($message['text'])?></div><?php endif;?>
<?php pe_list_header('Conferência documental','Documentos registrados','A listagem fica em primeiro plano; cadastro e manutenção dos documentos são feitos em modal.','Registrar documento','#peDocumentForm','folder-plus'); ?>
<?php pe_list_metrics($metrics,'#peDocumentFilters'); ?>
    <?php pe_list_filter_panel('peDocumentTable','Buscar candidato, documento, responsável ou observação... ',[
 ['key'=>'status','label'=>'Status','options'=>[''=>'Todos os status','Regular'=>'Regular','Pendente'=>'Pendente','Revisar'=>'Revisar','Vencido'=>'Vencido']],
 ['key'=>'tipo','label'=>'Documento','options'=>$typeOptions],
 ['key'=>'arquivo','label'=>'Arquivo','options'=>[''=>'Todos','Com arquivo'=>'Com arquivo','Sem arquivo'=>'Sem arquivo']],
],count($rows),'documento(s)'); ?>
<div class="pe-table-wrap"><div class="table-responsive"><table id="peDocumentTable" class="table align-middle pe-data-table pe-list-table" data-pe-list-table><thead><tr><th>Candidato</th><th>Documento</th><th>Arquivo</th><th>Validade</th><th>Status</th><th>Responsável</th></tr></thead><tbody>
<?php if(!$rows):?><tr class="pe-empty-row"><td colspan="6" class="text-center text-muted py-5">Nenhum documento registrado.</td></tr><?php endif;?>
<?php foreach($rows as $r):$record=$r;$record['__title']=$r['candidato'];$record['__subtitle']=$r['tipo'].' · '.$r['status'];$record['validade_formatada']=$r['validade']?date('d/m/Y',strtotime((string)$r['validade'])):'—';$record['arquivo_nome']=$r['nome_original']?:($r['arquivo_path']?'Arquivo protegido':'Sem arquivo');$record['download_url']=$r['arquivo_path']?'primeiro-emprego/documento.php?id='.(int)$r['id']:'';$arquivoSituacao=$r['arquivo_path']?'Com arquivo':'Sem arquivo';?>
<tr class="pe-list-row" tabindex="0" role="button" data-pe-list-row data-pe-actions-target="#peDocumentActions" data-pe-record="<?=pe_record_attr($record)?>" data-pe-filter-status="<?=pe_h((string)$r['status'])?>" data-pe-filter-tipo="<?=pe_h((string)$r['tipo'])?>" data-pe-filter-arquivo="<?=pe_h($arquivoSituacao)?>"><td data-label="Candidato"><strong><?=pe_h($r['candidato'])?></strong></td><td data-label="Documento"><?=pe_h($r['tipo'])?></td><td data-label="Arquivo"><?=pe_h($record['arquivo_nome'])?></td><td data-label="Validade"><?=pe_h($record['validade_formatada'])?></td><td data-label="Status"><?=pe_status_label($r['status'])?></td><td data-label="Responsável"><?=pe_h($r['registrado_por']?:'—')?></td></tr>
<?php endforeach;?></tbody></table></div><div class="pe-filter-empty" data-pe-filter-empty hidden>Nenhum documento corresponde aos filtros selecionados.</div></div>
<?php pe_crud_actions_dialog('peDocumentActions','Documento','#peDocumentView','#peDocumentForm','#peDocumentDelete'); ?>
<dialog class="pe-modal pe-modal--form" id="peDocumentForm" data-pe-create-title="Registrar documento" data-pe-edit-title="Editar documento"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Documentação</div><h2 data-pe-form-title>Registrar documento</h2><p>Arquivos são mantidos no storage privado do SIGAS.</p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><form method="post" enctype="multipart/form-data" class="pe-action-form" data-pe-record-form><?=pe_csrf_field()?><input type="hidden" name="pe_action" value="save_document"><input type="hidden" name="id" data-pe-field="id"><div class="pe-action-form-grid pe-action-form-grid--3"><div class="pe-field-span-2"><label class="form-label required">Candidato</label><select class="form-select" name="candidato_id" data-pe-field="candidato_id" required><option value="">Selecione...</option><?php foreach($candidates as $c):?><option value="<?=(int)$c['id']?>"><?=pe_h($c['nome'])?></option><?php endforeach;?></select></div><div><label class="form-label required">Documento</label><select class="form-select" name="tipo" data-pe-field="tipo" required><option value="">Selecione...</option><?php foreach(['Documento de identificação','CPF','Comprovante de residência','Comprovante de escolaridade','Currículo','NIS','Outro'] as $t):?><option><?=pe_h($t)?></option><?php endforeach;?></select></div><div><label class="form-label">Status</label><select class="form-select" name="status" data-pe-field="status"><?php foreach(['Regular','Pendente','Revisar','Vencido'] as $v):?><option><?=pe_h($v)?></option><?php endforeach;?></select></div><div><label class="form-label">Validade</label><input class="form-control" type="date" name="validade" data-pe-field="validade"></div><div><label class="form-label">Novo arquivo</label><input class="form-control" type="file" name="arquivo" accept=".pdf,.jpg,.jpeg,.png,.webp"><small class="pe-field-help">Ao editar, deixe vazio para manter o arquivo atual.</small></div><div class="pe-field-span-3"><label class="form-label">Observação</label><textarea class="form-control" name="observacao" data-pe-field="observacao" rows="3" maxlength="500"></textarea></div></div><footer class="pe-action-modal-footer"><button type="button" class="btn btn-light" data-pe-dialog-close>Cancelar</button><button class="btn btn-primary" type="submit"><i class="bi bi-folder-check"></i> Salvar documento</button></footer></form></div></div></dialog>
<dialog class="pe-modal pe-modal--view" id="peDocumentView"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Documento</div><h2 data-pe-current-title>Detalhes</h2><p data-pe-current-subtitle></p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><dl class="pe-modal-details pe-modal-details--2"><div><dt>Tipo</dt><dd data-pe-text="tipo">—</dd></div><div><dt>Status</dt><dd data-pe-text="status">—</dd></div><div><dt>Validade</dt><dd data-pe-text="validade_formatada">—</dd></div><div><dt>Responsável</dt><dd data-pe-text="registrado_por">—</dd></div><div><dt>Arquivo</dt><dd data-pe-text="arquivo_nome">—</dd></div><div><dt>Tipo MIME</dt><dd data-pe-text="mime_type">—</dd></div></dl><div class="pe-view-note"><strong>Observação</strong><p data-pe-text="observacao">—</p></div><a class="btn btn-outline-primary pe-record-download" href="#" data-pe-href="download_url" hidden><i class="bi bi-download"></i> Baixar arquivo</a></div></div></dialog>
<?php pe_delete_dialog('peDocumentDelete','documento','delete_document'); ?>
</section>
<?php $pageCustomContent=(string)ob_get_clean();
