<?php

declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/repository.php';
require_once dirname(__DIR__) . '/lib/list-ui.php';
$pageDefinition=['title'=>'Encaminhamentos','description'=>'Registro de candidatos encaminhados para oportunidades e acompanhamento do retorno.','demo'=>false,'show_states'=>false,'actions'=>[],'modal'=>['title'=>'Encaminhamento']];
$dbReady=pe_db_ready()&&pe_program_schema_ready();$message=null;$rows=[];$candidates=[];$vacancies=[];$partners=[];
if($dbReady){$pdo=pe_db();$candidates=pe_program_candidates($pdo);$vacancies=pe_vacancies($pdo);$partners=pe_partners($pdo);if($_SERVER['REQUEST_METHOD']==='POST'){try{pe_verify_csrf();$action=(string)($_POST['pe_action']??'');$id=(int)($_POST['id']??0);if($action==='save_referral'){if($id>0){pe_update_referral($pdo,$id,$_POST,pe_current_user_label());$message=['type'=>'success','text'=>'Encaminhamento atualizado com sucesso.'];}else{pe_save_referral($pdo,$_POST,pe_current_user_label());$message=['type'=>'success','text'=>'Encaminhamento registrado com sucesso.'];}}elseif($action==='delete_referral'){pe_delete_referral($pdo,$id);$message=['type'=>'success','text'=>'Encaminhamento excluído com sucesso.'];}}catch(Throwable $e){$message=['type'=>'danger','text'=>$e->getMessage()];}}$rows=pe_referrals($pdo);}
ob_start();
?>
<section class="content-card pe-form-card pe-page pe-list-page">
<?php if(!$dbReady):?><div class="alert alert-warning">Execute <code>database/primeiroEmprego/0003-primeiroEmprego-programa.sql</code>.</div><?php endif;?><?php if($message):?><div class="alert alert-<?=pe_h($message['type'])?>"><?=pe_h($message['text'])?></div><?php endif;?>
<?php pe_list_header('Seleção','Encaminhamentos registrados','Acompanhe os encaminhamentos. Todas as operações são abertas em modal.','Novo encaminhamento','#peReferralForm','send'); ?>
<?php pe_list_toolbar(count($rows),'Buscar candidato, vaga, instituição ou status...'); ?>
<div class="pe-table-wrap"><div class="table-responsive"><table class="table align-middle pe-data-table pe-list-table" data-pe-list-table><thead><tr><th>Candidato</th><th>Oportunidade</th><th>Instituição</th><th>Data</th><th>Responsável</th><th>Retorno</th><th>Status</th></tr></thead><tbody>
<?php if(!$rows):?><tr class="pe-empty-row"><td colspan="7" class="text-center text-muted py-5">Nenhum encaminhamento registrado.</td></tr><?php endif;?>
<?php foreach($rows as $r):$record=$r;$record['__title']=$r['candidato'];$record['__subtitle']=($r['vaga']?:'Sem vaga específica').' · '.($r['status']?:'Sem status');$record['data_encaminhamento_formatada']=date('d/m/Y',strtotime((string)$r['data_encaminhamento']));$record['data_retorno_formatada']=$r['data_retorno']?date('d/m/Y',strtotime((string)$r['data_retorno'])):'—';?>
<tr class="pe-list-row" tabindex="0" role="button" data-pe-list-row data-pe-actions-target="#peReferralActions" data-pe-record="<?=pe_record_attr($record)?>"><td data-label="Candidato"><strong><?=pe_h($r['candidato'])?></strong></td><td data-label="Oportunidade"><?=pe_h($r['vaga']?:'—')?></td><td data-label="Instituição"><?=pe_h($r['parceiro']?:'—')?></td><td data-label="Data"><?=pe_h($record['data_encaminhamento_formatada'])?></td><td data-label="Responsável"><?=pe_h($r['responsavel']?:'—')?></td><td data-label="Retorno"><?=pe_h($r['retorno']?:'Aguardando')?></td><td data-label="Status"><span class="pe-status-text"><?=pe_h($r['status'])?></span></td></tr>
<?php endforeach;?></tbody></table></div></div>
<?php pe_crud_actions_dialog('peReferralActions','Encaminhamento','#peReferralView','#peReferralForm','#peReferralDelete'); ?>
<dialog class="pe-modal pe-modal--form" id="peReferralForm" data-pe-create-title="Novo encaminhamento" data-pe-edit-title="Editar encaminhamento"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Seleção</div><h2 data-pe-form-title>Novo encaminhamento</h2><p>Registre a movimentação e o retorno do candidato.</p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><form method="post" class="pe-action-form" data-pe-record-form><?=pe_csrf_field()?><input type="hidden" name="pe_action" value="save_referral"><input type="hidden" name="id" data-pe-field="id"><div class="pe-action-form-grid pe-action-form-grid--3"><div class="pe-field-span-2"><label class="form-label required">Candidato</label><select class="form-select" name="candidato_id" data-pe-field="candidato_id" required><option value="">Selecione...</option><?php foreach($candidates as $c):?><option value="<?=(int)$c['id']?>"><?=pe_h($c['nome'])?> — <?=pe_h(pe_format_cpf($c['cpf']?:$c['cpf_informado']))?></option><?php endforeach;?></select></div><div><label class="form-label">Data</label><input class="form-control" type="date" name="data_encaminhamento" data-pe-field="data_encaminhamento" value="<?=date('Y-m-d')?>"></div><div><label class="form-label">Vaga</label><select class="form-select" name="vaga_id" data-pe-field="vaga_id"><option value="">Sem vaga específica</option><?php foreach($vacancies as $v):?><option value="<?=(int)$v['id']?>"><?=pe_h($v['cargo'])?> — <?=pe_h($v['parceiro']?:'Sem parceiro')?></option><?php endforeach;?></select></div><div><label class="form-label">Instituição</label><select class="form-select" name="parceiro_id" data-pe-field="parceiro_id"><option value="">Automática pela vaga</option><?php foreach($partners as $p):?><option value="<?=(int)$p['id']?>"><?=pe_h($p['nome'])?></option><?php endforeach;?></select></div><div><label class="form-label">Status</label><select class="form-select" name="status" data-pe-field="status"><?php foreach(['Pendente','Encaminhado','Entrevista marcada','Aprovado','Não selecionado'] as $v):?><option><?=pe_h($v)?></option><?php endforeach;?></select></div><div><label class="form-label">Data de retorno</label><input class="form-control" type="date" name="data_retorno" data-pe-field="data_retorno"></div><div class="pe-field-span-2"><label class="form-label">Retorno</label><textarea class="form-control" name="retorno" data-pe-field="retorno" rows="3"></textarea></div></div><footer class="pe-action-modal-footer"><button type="button" class="btn btn-light" data-pe-dialog-close>Cancelar</button><button class="btn btn-primary" type="submit"><i class="bi bi-send"></i> Salvar encaminhamento</button></footer></form></div></div></dialog>
<dialog class="pe-modal pe-modal--view" id="peReferralView"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Encaminhamento</div><h2 data-pe-current-title>Detalhes</h2><p data-pe-current-subtitle></p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><dl class="pe-modal-details pe-modal-details--2"><div><dt>Oportunidade</dt><dd data-pe-text="vaga">—</dd></div><div><dt>Instituição</dt><dd data-pe-text="parceiro">—</dd></div><div><dt>Data</dt><dd data-pe-text="data_encaminhamento_formatada">—</dd></div><div><dt>Status</dt><dd data-pe-text="status">—</dd></div><div><dt>Responsável</dt><dd data-pe-text="responsavel">—</dd></div><div><dt>Data de retorno</dt><dd data-pe-text="data_retorno_formatada">—</dd></div></dl><div class="pe-view-note"><strong>Retorno</strong><p data-pe-text="retorno">Aguardando</p></div></div></div></dialog>
<?php pe_delete_dialog('peReferralDelete','encaminhamento','delete_referral'); ?>
</section>
<?php $pageCustomContent=(string)ob_get_clean();
