<?php

declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/repository.php';
require_once dirname(__DIR__) . '/lib/list-ui.php';
$pageDefinition=['title'=>'Frequência','description'=>'Registro mensal de presença dos participantes do programa.','demo'=>false,'show_states'=>false,'actions'=>[],'modal'=>['title'=>'Frequência']];
$dbReady=pe_db_ready()&&pe_program_schema_ready();$message=null;$rows=[];$candidates=[];
if($dbReady){$pdo=pe_db();$candidates=pe_program_candidates($pdo);if($_SERVER['REQUEST_METHOD']==='POST'){try{pe_verify_csrf();$action=(string)($_POST['pe_action']??'');$id=(int)($_POST['id']??0);if($action==='save_attendance'){if($id>0){pe_update_attendance($pdo,$id,$_POST,pe_current_user_label());$message=['type'=>'success','text'=>'Frequência atualizada com sucesso.'];}else{pe_save_attendance($pdo,$_POST,pe_current_user_label());$message=['type'=>'success','text'=>'Frequência salva com sucesso.'];}}elseif($action==='delete_attendance'){pe_delete_attendance($pdo,$id);$message=['type'=>'success','text'=>'Frequência excluída com sucesso.'];}}catch(Throwable $e){$message=['type'=>'danger','text'=>$e->getMessage()];}}$rows=pe_attendance_rows($pdo);}
$avgFrequency=count($rows)>0?array_sum(array_map(static fn($r)=>(float)($r['percentual']??0),$rows))/count($rows):0;
$currentCompetence=date('Y-m');
$metrics=[
 ['label'=>'Registros','value'=>count($rows),'hint'=>'competências lançadas','tone'=>'neutral'],
 ['label'=>'Regulares','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Regular'),'hint'=>'acima do mínimo','tone'=>'success','filter_key'=>'status','filter_value'=>'Regular'],
 ['label'=>'Atenção','value'=>pe_count_rows($rows,fn($r)=>(string)($r['status']??'')==='Atenção'),'hint'=>'abaixo do mínimo','tone'=>'warning','filter_key'=>'status','filter_value'=>'Atenção'],
 ['label'=>'Média geral','value'=>number_format($avgFrequency,1,',','.').'%','hint'=>'dos registros exibidos','tone'=>$avgFrequency>=75?'success':'warning'],
 ['label'=>'≥ 90%','value'=>pe_count_rows($rows,fn($r)=>(float)($r['percentual']??0)>=90),'hint'=>'frequência alta','tone'=>'success','filter_key'=>'faixa','filter_value'=>'90+'],
 ['label'=>'Competência atual','value'=>pe_count_rows($rows,fn($r)=>(string)($r['competencia']??'')===$currentCompetence),'hint'=>$currentCompetence,'tone'=>'info','filter_key'=>'competencia','filter_value'=>$currentCompetence],
];
$competenceOptions=pe_filter_options($rows,'competencia','Todas as competências');
$localOptions=pe_filter_options($rows,'parceiro','Todos os locais');
ob_start();?>
<section class="content-card pe-form-card pe-page pe-list-page">
<?php if(!$dbReady):?><div class="alert alert-warning">Execute <code>database/primeiroEmprego/0003-primeiroEmprego-programa.sql</code>.</div><?php endif;?><?php if($message):?><div class="alert alert-<?=pe_h($message['type'])?>"><?=pe_h($message['text'])?></div><?php endif;?>
<?php pe_list_header('Controle mensal','Frequência dos participantes','Consulte as competências registradas; inclusão, edição e exclusão são feitas em modal.','Registrar frequência','#peAttendanceForm','calendar-check'); ?>
<?php pe_list_metrics($metrics,'#peAttendanceFilters'); ?>
    <?php pe_list_filter_panel('peAttendanceTable','Buscar participante, competência, local ou responsável...',[
 ['key'=>'competencia','label'=>'Competência','options'=>$competenceOptions],
 ['key'=>'status','label'=>'Situação','options'=>[''=>'Todas as situações','Regular'=>'Regular','Atenção'=>'Atenção']],
 ['key'=>'local','label'=>'Local','options'=>$localOptions],
 ['key'=>'faixa','label'=>'Faixa','options'=>[''=>'Todas as faixas','90+'=>'90% ou mais','75-89'=>'75% a 89,9%','<75'=>'Abaixo de 75%']],
],count($rows),'registro(s)'); ?>
<div class="pe-table-wrap"><div class="table-responsive"><table id="peAttendanceTable" class="table align-middle pe-data-table pe-list-table" data-pe-list-table><thead><tr><th>Competência</th><th>Participante</th><th>Local</th><th>Previstos</th><th>Presenças</th><th>Faltas</th><th>Frequência</th><th>Status</th></tr></thead><tbody>
<?php if(!$rows):?><tr class="pe-empty-row"><td colspan="8" class="text-center text-muted py-5">Nenhuma frequência registrada.</td></tr><?php endif;?>
<?php foreach($rows as $r):$record=$r;$record['__title']=$r['candidato'];$record['__subtitle']=$r['competencia'].' · '.$r['status'];$record['percentual_formatado']=number_format((float)$r['percentual'],1,',','.').'%';$pct=(float)$r['percentual'];$faixa=$pct>=90?'90+':($pct>=75?'75-89':'<75');?>
<tr class="pe-list-row" tabindex="0" role="button" data-pe-list-row data-pe-actions-target="#peAttendanceActions" data-pe-record="<?=pe_record_attr($record)?>" data-pe-filter-competencia="<?=pe_h((string)$r['competencia'])?>" data-pe-filter-status="<?=pe_h((string)$r['status'])?>" data-pe-filter-local="<?=pe_h((string)($r['parceiro']??''))?>" data-pe-filter-faixa="<?=pe_h($faixa)?>"><td data-label="Competência"><?=pe_h($r['competencia'])?></td><td data-label="Participante"><strong><?=pe_h($r['candidato'])?></strong></td><td data-label="Local"><?=pe_h($r['parceiro']?:'—')?></td><td data-label="Previstos"><?=(int)$r['dias_previstos']?></td><td data-label="Presenças"><?=(int)$r['presencas']?></td><td data-label="Faltas"><?=(int)$r['faltas']?></td><td data-label="Frequência"><strong class="<?=pe_h(pe_status_class($r['status']))?>"><?=pe_h($record['percentual_formatado'])?></strong></td><td data-label="Status"><?=pe_status_label($r['status'])?></td></tr>
<?php endforeach;?></tbody></table></div><div class="pe-filter-empty" data-pe-filter-empty hidden>Nenhuma frequência corresponde aos filtros selecionados.</div></div>
<?php pe_crud_actions_dialog('peAttendanceActions','Frequência','#peAttendanceView','#peAttendanceForm','#peAttendanceDelete'); ?>
<dialog class="pe-modal pe-modal--form" id="peAttendanceForm" data-pe-create-title="Registrar frequência" data-pe-edit-title="Editar frequência"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Frequência</div><h2 data-pe-form-title>Registrar frequência</h2><p>Informe a competência e os dias do participante.</p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><form method="post" class="pe-action-form" data-pe-record-form><?=pe_csrf_field()?><input type="hidden" name="pe_action" value="save_attendance"><input type="hidden" name="id" data-pe-field="id"><div class="pe-action-form-grid pe-action-form-grid--3"><div class="pe-field-span-2"><label class="form-label required">Participante</label><select class="form-select" name="candidato_id" data-pe-field="candidato_id" required><option value="">Selecione...</option><?php foreach($candidates as $c):?><option value="<?=(int)$c['id']?>"><?=pe_h($c['nome'])?></option><?php endforeach;?></select></div><div><label class="form-label required">Competência</label><input class="form-control" type="month" name="competencia" data-pe-field="competencia" value="<?=date('Y-m')?>" required></div><div><label class="form-label">Dias previstos</label><input class="form-control" type="number" min="0" max="31" name="dias_previstos" data-pe-field="dias_previstos" value="22"></div><div><label class="form-label">Presenças</label><input class="form-control" type="number" min="0" max="31" name="presencas" data-pe-field="presencas" value="0"></div><div><label class="form-label">Faltas</label><input class="form-control" type="number" min="0" max="31" name="faltas" data-pe-field="faltas" value="0"></div><div class="pe-field-span-3"><label class="form-label">Observação</label><textarea class="form-control" name="observacao" data-pe-field="observacao" rows="3" maxlength="500"></textarea></div></div><footer class="pe-action-modal-footer"><button type="button" class="btn btn-light" data-pe-dialog-close>Cancelar</button><button class="btn btn-primary" type="submit"><i class="bi bi-floppy"></i> Salvar frequência</button></footer></form></div></div></dialog>
<dialog class="pe-modal pe-modal--view" id="peAttendanceView"><div class="pe-modal__shell"><header class="pe-modal__header"><div><div class="card-kicker">Frequência</div><h2 data-pe-current-title>Detalhes</h2><p data-pe-current-subtitle></p></div><button type="button" class="pe-modal__close" data-pe-dialog-close><i class="bi bi-x-lg"></i></button></header><div class="pe-modal__body"><dl class="pe-modal-details pe-modal-details--3"><div><dt>Competência</dt><dd data-pe-text="competencia">—</dd></div><div><dt>Local</dt><dd data-pe-text="parceiro">—</dd></div><div><dt>Status</dt><dd data-pe-text="status">—</dd></div><div><dt>Dias previstos</dt><dd data-pe-text="dias_previstos">0</dd></div><div><dt>Presenças</dt><dd data-pe-text="presencas">0</dd></div><div><dt>Faltas</dt><dd data-pe-text="faltas">0</dd></div><div><dt>Percentual</dt><dd data-pe-text="percentual_formatado">—</dd></div><div><dt>Responsável</dt><dd data-pe-text="registrado_por">—</dd></div></dl><div class="pe-view-note"><strong>Observação</strong><p data-pe-text="observacao">—</p></div></div></div></dialog>
<?php pe_delete_dialog('peAttendanceDelete','frequência','delete_attendance'); ?>
</section>
<?php $pageCustomContent=(string)ob_get_clean();
