<?php
return [
    'recepcao' => [
        'dashboard' => 'recepcao/dashboard',
        'novoProtocolo' => 'recepcao/novoProtocolo',
        'clientes' => 'recepcao/clientes',
        'protocolos' => 'recepcao/protocolos',
        'documentos' => 'recepcao/documentos',
        'encaminhar' => 'recepcao/encaminhar',
        'pendencias' => 'recepcao/pendencias',
        'relatorios' => 'recepcao/relatorios',
        'configuracoes' => 'recepcao/configuracoes',
    ],
    'administrativo' => [
        'dashboard' => 'administrativo/dashboard',
        'orcamentos' => 'administrativo/orcamentos',
        'orcamentoCadastrar' => 'administrativo/orcamentoCadastrar',
        'orcamentoEditar' => 'administrativo/orcamentoEditar',
        'orcamentoVisualizar' => 'administrativo/orcamentoVisualizar',
        'protocolosRecebidos' => 'administrativo/protocolosRecebidos',
        'protocoloVisualizar' => 'administrativo/protocoloVisualizar',
        'analises' => 'administrativo/analises',
        'clientes' => 'administrativo/clientes',
        'clienteCadastrar' => 'administrativo/clienteCadastrar',
        'clienteEditar' => 'administrativo/clienteEditar',
        'clienteVisualizar' => 'administrativo/clienteVisualizar',
        'documentos' => 'administrativo/documentos',
        'documentoVisualizar' => 'administrativo/documentoVisualizar',
        'pendencias' => 'administrativo/pendencias',
        'pendenciaCadastrar' => 'administrativo/pendenciaCadastrar',
        'pendenciaEditar' => 'administrativo/pendenciaEditar',
        'pendenciaVisualizar' => 'administrativo/pendenciaVisualizar',
        'relatorios' => 'administrativo/relatorios',
        'configuracoes' => 'administrativo/configurações',
    ],
    'dono' => [
        'dashboard' => 'dono/dashboard',
        'usuarios' => 'dono/usuarios',
        'permissoes' => 'dono/permissoes',
        'relatorios' => 'dono/relatorios',
        'configuracoes' => 'dono/configuracoes',
    ],
    'auth' => [
        'login' => 'auth/login',
    ],
];
