<?php
return [
    'recepcao' => [
        'dashboard' => 'recepcao/dashboard',
        'novoProtocolo' => 'recepcao/novoProtocolo',
        'protocoloVisualizar' => 'recepcao/protocoloVisualizar',
        'protocoloEditar' => 'recepcao/protocoloEditar',
        'clientes' => 'recepcao/clientes',
        'clienteCadastrar' => 'recepcao/clienteCadastrar',
        'clienteVisualizar' => 'recepcao/clienteVisualizar',
        'clienteEditar' => 'recepcao/clienteEditar',
        'protocolos' => 'recepcao/protocolos',
        'documentos' => 'recepcao/documentos',
        'documentoVisualizar' => 'recepcao/documentoVisualizar',
        'documentoEditar' => 'recepcao/documentoEditar',
        'encaminhar' => 'recepcao/encaminhar',
        'pendencias' => 'recepcao/pendencias',
        'pendenciaCadastrar' => 'recepcao/pendenciaCadastrar',
        'pendenciaVisualizar' => 'recepcao/pendenciaVisualizar',
        'pendenciaEditar' => 'recepcao/pendenciaEditar',
        'relatorios' => 'recepcao/relatorios',
        'configuracoes' => 'recepcao/configuracoes',
    ],
    'administrativo' => [
        'dashboard' => 'administrativo/dashboard',
        'orcamentos' => 'administrativo/orcamentos',
        'orcamentoCadastrar' => 'administrativo/orcamentoCadastrar',
        'orcamentoEditar' => 'administrativo/orcamentoEditar',
        'orcamentoVisualizar' => 'administrativo/orcamentoVisualizar',
        'protocolosRecebidos' => 'administrativo/protocolosRecebidos',
        'protocoloVisualizar' => 'administrativo/protocoloVisualizar',
        'analises' => 'administrativo/analises',
        'clientes' => 'administrativo/clientes',
        'clienteCadastrar' => 'administrativo/clienteCadastrar',
        'clienteEditar' => 'administrativo/clienteEditar',
        'clienteVisualizar' => 'administrativo/clienteVisualizar',
        'documentos' => 'administrativo/documentos',
        'documentoVisualizar' => 'administrativo/documentoVisualizar',
        'pendencias' => 'administrativo/pendencias',
        'pendenciaCadastrar' => 'administrativo/pendenciaCadastrar',
        'pendenciaEditar' => 'administrativo/pendenciaEditar',
        'pendenciaVisualizar' => 'administrativo/pendenciaVisualizar',
        'relatorios' => 'administrativo/relatorios',
        'configuracoes' => 'administrativo/configurações',
    ],
    'dono' => [
        'dashboard' => 'dono/dashboard',
        'clientes' => 'dono/clientes',
        'usuarios' => 'dono/usuarios',
        'usuarioCadastrar' => 'dono/usuarioCadastrar',
        'usuarioVisualizar' => 'dono/usuarioVisualizar',
        'usuarioEditar' => 'dono/usuarioEditar',
        'permissoes' => 'dono/permissoes',
        'permissaoCadastrar' => 'dono/permissaoCadastrar',
        'permissaoVisualizar' => 'dono/permissaoVisualizar',
        'permissaoEditar' => 'dono/permissaoEditar',
        'tiposServicos' => 'dono/tiposServicos',
        'tipoServicoCadastrar' => 'dono/tipoServicoCadastrar',
        'tipoServicoEditar' => 'dono/tipoServicoEditar',
        'tipoServicoVisualizar' => 'dono/tipoServicoVisualizar',
        'relatorios' => 'dono/relatorios',
        'configuracoes' => 'dono/configuracoes',
    ],
    'auth' => [
        'login' => 'auth/login',
    ],
];
