<?php
declare(strict_types=1);

namespace App\Admin\DTO;

use InvalidArgumentException;

final class CompanyAdminFormData
{
    private const STATUSES=['ativo','pendente','inativo','bloqueado'];
    private array $values;
    private function __construct(array $values){$this->values=$values;}
    public static function fromArray(array $data): self { $clean=static function(string $key,int $max)use($data):?string{$v=trim((string)($data[$key]??''));if($v==='')return null;if(str_contains($v,"\0")||$v!==strip_tags($v)||mb_strlen($v)>$max)throw new InvalidArgumentException('Dados da empresa inválidos.');return $v;};$document=preg_replace('/\D+/','',(string)($data['documento']??''))??'';if($document!==''&&!self::validDocument($document))throw new InvalidArgumentException('CPF ou CNPJ inválido.');$email=$clean('email',150);if($email!==null&&filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new InvalidArgumentException('E-mail inválido.');$uf=strtoupper((string)($clean('endereco_uf',2)??''));if($uf!==''&&preg_match('/^[A-Z]{2}$/',$uf)!==1)throw new InvalidArgumentException('UF inválida.');$cep=preg_replace('/\D+/','',(string)($data['endereco_cep']??''))??'';if($cep!==''&&strlen($cep)!==8)throw new InvalidArgumentException('CEP inválido.');$status=(string)($data['status']??'pendente');if(!in_array($status,self::STATUSES,true))throw new InvalidArgumentException('Status inválido.');$person=(string)($data['tipo_pessoa']??'juridica');if(!in_array($person,['fisica','juridica'],true))throw new InvalidArgumentException('Tipo de pessoa inválido.');$rawResponsible=trim((string)($data['responsavel_usuario_id']??''));if($rawResponsible!==''&&!is_int(filter_var($rawResponsible,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])))throw new InvalidArgumentException('Usuário responsável inválido.');$phone=preg_replace('/[^0-9+()\-\s]/','',(string)($data['telefone']??''))??'';$values=['razao_social'=>$clean('razao_social',150),'nome_fantasia'=>$clean('nome_fantasia',150),'documento'=>$document===''?null:$document,'tipo_pessoa'=>$person,'segmento'=>$clean('segmento',100),'contato'=>$clean('contato',150),'telefone'=>$phone===''?null:$phone,'email'=>$email,'inscricao_estadual'=>$clean('inscricao_estadual',40),'inscricao_municipal'=>$clean('inscricao_municipal',40),'endereco_logradouro'=>$clean('endereco_logradouro',150),'endereco_numero'=>$clean('endereco_numero',30),'endereco_complemento'=>$clean('endereco_complemento',100),'endereco_bairro'=>$clean('endereco_bairro',100),'endereco_cidade'=>$clean('endereco_cidade',100),'endereco_uf'=>$uf===''?null:$uf,'endereco_cep'=>$cep===''?null:$cep,'status'=>$status,'responsavel_usuario_id'=>self::positive($rawResponsible)];if($values['razao_social']===null)throw new InvalidArgumentException('Razão social é obrigatória.');return new self($values); }
    public function values():array{return $this->values;} public function status():string{return $this->values['status'];} public function responsibleUserId():?int{return $this->values['responsavel_usuario_id'];}
    private static function positive(mixed $v):?int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return is_int($id)?$id:null;}private static function validDocument(string $d):bool{if(preg_match('/^(\d)\1+$/',$d))return false;if(strlen($d)===11){for($p=9;$p<11;$p++){ $s=0;for($i=0;$i<$p;$i++)$s+=(int)$d[$i]*(($p+1)-$i);if((int)$d[$p]!==((10*$s)%11)%10)return false;}return true;}if(strlen($d)===14){foreach([12=>[5,4,3,2,9,8,7,6,5,4,3,2],13=>[6,5,4,3,2,9,8,7,6,5,4,3,2]] as $p=>$w){$s=0;foreach($w as $i=>$x)$s+=(int)$d[$i]*$x;$r=$s%11;if((int)$d[$p]!==($r<2?0:11-$r))return false;}return true;}return false;}
}
