<?php
const WHATSAPP_CLOUD_API_TOKEN = '';
const WHATSAPP_PHONE_NUMBER_ID = '';
const WHATSAPP_API_VERSION = 'v21.0';
const TWILIO_ACCOUNT_SID = '';
const TWILIO_AUTH_TOKEN = '';
const TWILIO_WHATSAPP_FROM = '';
const EVOLUTION_API_URL = '';
const EVOLUTION_API_KEY = '';
const EVOLUTION_INSTANCE = 'arteflor';
